recipes-devtools/clang/clang_git.bb
The copyright date in projects/compiler-rt/LICENSE.TXT changed from
2014 to 2015.
=> Update license md5 checksum

recipes-devtools/clang/clang.inc, recipes-devtools/clang/clang_git.bb, recipes-devtools/clang/compiler-rt_git.bb, recipes-devtools/clang/libcxx_git.bb, recipes-devtools/clang/libcxxabi_git.bb, recipes-devtools/clang/llvm-libunwind_git.bb
Signed-off-by: Yi Qingliang <niqingliang2003@gmail.com>
=> use variable 'CLANG_GIT' and 'CLANG_GIT_PROTOCOL'

recipes-devtools/clang/clang_git.bb
for qa problem: installed-vs-shipped
=> remove empty directory when installing nativesdk

recipes-devtools/clang/clang_git.bb, recipes-devtools/clang/lld_git.bb, recipes-devtools/clang/llvm-common/llvm-config
Hi
I want to build mesa with meta-clang instead that with the already too old llvm3.3. I have made some changes to your tree that I think could be interesting for other people.
I have already send the patches to the mailing list, but maybe you prefer this method.
Regards!
=> Initial work to build mesa with clang

recipes-devtools/clang/libcxx_git.bb
Allow libunwind to be turned off and on using PACKAGECONFIG
Default to ON
Signed-off-by: Michael Davis <michael.davis@essvote.com>
=> libcxx: Add libunwind to PACKAGECONFIG

conf/nonclangable.conf
=> nonclangable: more packages are now buildable with clang 7.0

classes/clang.bbclass, conf/nonclangable.conf, recipes-core/meta/meta-environment.bbappend, recipes-devtools/clang/clang-cross-canadian_git.bb, recipes-devtools/clang/clang-cross_git.bb, recipes-devtools/clang/clang-crosssdk_git.bb, recipes-devtools/clang/clang/0016-clang-Append-libunwind-to-compiler-rt-for-linking.patch, recipes-devtools/clang/clang/0017-llvm-AARCH64-Add-support-for-.dword-directives.patch, recipes-devtools/clang/common.inc
add .dword support for aarch64
=> Link with libunwind when using compiler-rt

recipes-devtools/clang/clang.inc
=> clang: Update to latest on 8.x branch

recipes-devtools/clang/clang_git.bb
Fixes https://github.com/kraj/meta-clang/issues/115
=> Fix clang for armhf on target

recipes-devtools/clang/clang.inc
=> clang: Update to latest release/9.x branch

conf/nonclangable.conf
=> nonclangable: Link harfbuzz with latomic on riscv64

recipes-devtools/clang/clang.inc, recipes-devtools/clang/clang/0001-lldb-Add-lxml2-to-linker-cmdline-of-xml-is-found.patch, recipes-devtools/clang/clang/0002-libcxxabi-Find-libunwind-headers-when-LIBCXXABI_LIBU.patch, recipes-devtools/clang/clang/0003-compiler-rt-support-a-new-embedded-linux-target.patch, recipes-devtools/clang/clang/0004-compiler-rt-Simplify-cross-compilation.-Don-t-use-na.patch, recipes-devtools/clang/clang/0005-compiler-rt-Disable-tsan-on-OE-glibc.patch, recipes-devtools/clang/clang/0006-llvm-TargetLibraryInfo-Undefine-libc-functions-if-th.patch, recipes-devtools/clang/clang/0007-llvm-allow-env-override-of-exe-path.patch, recipes-devtools/clang/clang/0008-llvm-Enhance-path-prefix-mapping.patch, recipes-devtools/clang/clang/0009-clang-Enable-SSP-and-PIE-by-default.patch, recipes-devtools/clang/clang/0010-clang-driver-Use-lib-for-ldso-on-OE.patch, recipes-devtools/clang/clang/0011-clang-Driver-tools.cpp-Add-lssp_nonshared-on-musl.patch, recipes-devtools/clang/clang/0012-clang-musl-ppc-does-not-support-128-bit-long-double.patch, recipes-devtools/clang/clang/0013-clang-Prepend-trailing-to-sysroot.patch, recipes-devtools/clang/clang/0014-clang-Look-inside-the-target-sysroot-for-compiler-ru.patch, recipes-devtools/clang/clang/0015-clang-Define-releative-gcc-installation-dir.patch, recipes-devtools/clang/clang/0016-clang-Fix-ldso-for-musl-on-x86-and-x32-architectures.patch, recipes-devtools/clang/clang/0017-clang-scan-view-needs-python-2.x.patch, recipes-devtools/clang/clang/0018-clang-Initial-implementation-of-fmacro-prefix-map-an.patch, recipes-devtools/clang/clang/0019-clang-Add-lpthread-and-ldl-along-with-lunwind-for-st.patch, recipes-devtools/clang/clang/0020-clang-default-to-lp64d-ABI-and-rv64gc-ISA.patch, recipes-devtools/clang/clang/0021-lldb-Do-not-look-for-interpreter.patch, recipes-devtools/clang/clang_git.bb, recipes-devtools/clang/common.inc
Update at the same time to latest on 9.x
=> clang: Define PYTHON_LIBRARY and PYTHON_INCLUDE_DIR

recipes-devtools/clang/clang_git.bb
=> clang: Add libedit via packageconfig and turn it on by default

dynamic-layers/openembedded-layer/recipes-kernel/kernel-selftest/kernel-selftest.bbappend
=> kernel-selftest: Enable build by setting COMPATIBLE_HOST regexp

recipes-devtools/clang/clang_git.bb
=> clang: add rtti and eh as packageconfig

recipes-devtools/clang/clang/0001-lldb-Add-lxml2-to-linker-cmdline-of-xml-is-found.patch, recipes-devtools/clang/clang/0002-libcxxabi-Find-libunwind-headers-when-LIBCXXABI_LIBU.patch, recipes-devtools/clang/clang/0003-compiler-rt-support-a-new-embedded-linux-target.patch, recipes-devtools/clang/clang/0004-compiler-rt-Simplify-cross-compilation.-Don-t-use-na.patch, recipes-devtools/clang/clang/0005-compiler-rt-Disable-tsan-on-OE-glibc.patch, recipes-devtools/clang/clang/0006-llvm-TargetLibraryInfo-Undefine-libc-functions-if-th.patch, recipes-devtools/clang/clang/0007-llvm-allow-env-override-of-exe-path.patch, recipes-devtools/clang/clang/0008-llvm-Enhance-path-prefix-mapping.patch, recipes-devtools/clang/clang/0009-clang-Enable-SSP-and-PIE-by-default.patch, recipes-devtools/clang/clang/0010-clang-driver-Use-lib-for-ldso-on-OE.patch, recipes-devtools/clang/clang/0011-clang-Driver-tools.cpp-Add-lssp_nonshared-on-musl.patch, recipes-devtools/clang/clang/0012-clang-musl-ppc-does-not-support-128-bit-long-double.patch, recipes-devtools/clang/clang/0013-clang-Prepend-trailing-to-sysroot.patch, recipes-devtools/clang/clang/0014-clang-Look-inside-the-target-sysroot-for-compiler-ru.patch, recipes-devtools/clang/clang/0015-clang-Define-releative-gcc-installation-dir.patch, recipes-devtools/clang/clang/0016-clang-Fix-ldso-for-musl-on-x86-and-x32-architectures.patch, recipes-devtools/clang/clang/0017-clang-scan-view-needs-python-2.x.patch, recipes-devtools/clang/clang/0018-clang-Initial-implementation-of-fmacro-prefix-map-an.patch, recipes-devtools/clang/clang/0019-clang-Add-lpthread-and-ldl-along-with-lunwind-for-st.patch, recipes-devtools/clang/clang/0020-clang-default-to-lp64d-ABI-and-rv64gc-ISA.patch, recipes-devtools/clang/clang/0021-Driver-Prioritize-SYSROOT-usr-include-over-RESOURCE_.patch, recipes-devtools/clang/clang/0022-RISCV-Add-support-for-floating-point-registers-in-in.patch, recipes-devtools/clang/clang/0023-Pass-PYTHON_EXECUTABLE-when-cross-compiling-for-nati.patch, recipes-devtools/clang/clang/0024-openmp-Recognise-ARMv7ve-machine-arch.patch, recipes-devtools/clang/common.inc
Refresh patches on latest release/9.x branch
=> clang: Fix openmp build on armv7ve

conf/layer.conf
=> layer.conf: Drop release older than zeus from compatiblity

recipes-devtools/clang/clang_git.bb, recipes-devtools/clang/llvm-common/llvm-config
Cherry-pick eea276a91c2594b573c82bf82587aa0e502e804f back to warrior
Signed-off-by: Michael Davis <michael.davis@essvote.com>
=> clang: Fix cmake exports not finding native binaries Issue #230

recipes-devtools/clang/clang.inc, recipes-devtools/clang/clang_git.bb
=> clang: Update to 9.0.1-rc2

conf/nonclangable.conf
=> python3,x64: Can be compiled with clang9

recipes-devtools/clang/clang/0025-llvm-Let-llvm-ar-name-contain-lib.patch
=> clang: Update tool rename patch to match upstream one

recipes-devtools/clang/clang.inc
=> clang: Update to 9.0.1 RC3

recipes-devtools/clang/libcxx_git.bb
=> libcxx: Fix build on architectures with baselib != lib

recipes-devtools/clang/clang/0027-Fix-sanitizer-common-build-with-glibc-2.31.patch, recipes-devtools/clang/common.inc
=> compiler-rt: Fix build with glibc 2.31

recipes-devtools/clang/compiler-rt_git.bb
=> compiler-rt: Depend on libcrypt for sanitizers

.drone.yml
=> drone: Switch trunk ci to master branch

recipes-devtools/clang/openmp_git.bb
=> openmp: Disable ompt tools on targets where ompt is not supported

conf/layer.conf
Add LAYERDEPENDS to core as per README.md .
=> Add LAYERDEPENDS

.drone.yml, conf/layer.conf
This ensures that clangsdk does not inserts itself unless user asks for
Fixes #234
=> layer.conf: Mark CLANGSDK 0 by default

conf/nonclangable.conf
It can build with clang now a days
=> wpewebkit: Enable clang

recipes-devtools/clang/clang_git.bb, recipes-devtools/clang/libcxx_git.bb
=> Fix unwinder

recipes-devtools/clang/clang_git.bb, recipes-devtools/clang/libcxx_git.bb
=> unwinder support fixes

.drone.yml, recipes-devtools/clang/libcxx_git.bb
=> Fix libcxx on rv32

dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc/0001-Replace-kprobe-function-blk_account_io_completion-to.patch, dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc/0001-tools-trace.py-Fix-failing-to-exit.patch, dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc_0.15.0.bb
=> Fix biosnoop and trace

README.md
=> README: Add intruction to build with poky

README.md
=> README: Fix URL links to actions

classes/clang.bbclass, recipes-devtools/clang/clang/0026-clang-Use-python3-in-python-scripts.patch, recipes-devtools/clang/clang_git.bb, recipes-devtools/clang/common.inc
This helps ensure that lldb-server gets correct tripets on target
---
=> clang: Define LLVM_HOST_TRIPLE

recipes-graphics/mesa/mesa_%.bbappend
=> mesa: Depend on elfutils regardless of llvm check

dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc_0.17.0.bb
To support kernel v5.9 and remove patches that have been merged upstream.
Signed-off-by: He Zhe <zhe.he@windriver.com>
---
=> bcc: Upgrade 0.15.0 -> 0.17.0

recipes-devtools/clang/clang_git.bb, recipes-devtools/clang/libcxx_git.bb
Backport the fix for bug #332 to the zeus branch.
---
=> Zeus backport of 332 fix

recipes-devtools/clang/clang/0025-libcxx-Define-__NR_futex-to-be-__NR_futex_time64-on-.patch, recipes-devtools/rpm/rpm_%.bbappend
=> clang: Fix the __NR_futex_time64 patch

conf/nonclangable.conf, recipes-devtools/rpm/rpm_%.bbappend
=> Fix some mips build failures

conf/nonclangable.conf, recipes-devtools/clang/clang.inc
=> Update to clang 11.0.1-rc2 and fix pulseaudio build

classes/clang.bbclass, conf/layer.conf, recipes-devtools/clang/clang.inc
=> Upgrade to 11.1.0 RC2

recipes-devtools/clang/clang/0001-Fix-libclc-to-look-for-python3-explicitly.patch, recipes-devtools/clang/clang/D95527_against_11.x.patch, recipes-devtools/clang/common.inc, recipes-devtools/clang/libclc_git.bb
This is a pre-requisite to enable OpenCL in Mesa.
Signed-off-by: Zoltán Böszörményi <zboszor@pr.hu>
---
=> libclc: Add recipe

README.md, recipes-devtools/clang/clang/0026-For-x86_64-set-Yocto-based-GCC-install-search-path.patch, recipes-devtools/clang/clang/0029-llvm-Recognize-yoe-and-poky-as-OE-distro.patch, recipes-devtools/clang/llvm-project-source.inc
Only a draft, because for some reason this still doesn't work correctly and compiler-rt is failing with:
http://errors.yoctoproject.org/Errors/Details/574365/
=> Support more TARGET_VENDOR values

recipes-devtools/clang/clang/0030-compiler-rt-Use-mcr-based-barrier-on-armv6.patch, recipes-devtools/clang/common.inc
=> compiler-rt: Fix build on armv6

dynamic-layers/browser-layer/recipes-browser/chromium-ozone-wayland_%.bbappend, dynamic-layers/browser-layer/recipes-browser/chromium-x11_%.bbappend
These changes have been proposed for meta-browser itself see
https://github.com/OSSystems/meta-browser/pull/489
---
=> Drop browser-layer from dynamic layers

conf/nonclangable.conf, recipes-devtools/clang/clang.inc, recipes-devtools/clang/clang_git.bb
=> Dont use clang for ell/iwd and do not use lld when building nativesdk clang

conf/layer.conf
=> layer.conf: Add 3.4 as supported release

README.md, classes/clang.bbclass, conf/nonclangable.conf, recipes-devtools/clang/compiler-rt-sanitizers_git.bb, recipes-devtools/clang/compiler-rt_git.bb
=> Add support for building compiler-rt sanitizers

recipes-devtools/clang/clang/0033-Import-upstream-patch-to-re-add-Reporter.py.patch, recipes-devtools/clang/common.inc
See: https://github.com/kraj/meta-clang/issues/466
=> Fix for Reporter.py

conf/nonclangable.conf
=> ppc64 fixes

conf/nonclangable.conf, recipes-devtools/clang/clang.inc
=> update to latest 13.x

classes/clang.bbclass, conf/nonclangable.conf
=> Further fixes for new override syntax

dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace/0001-support-clang-upto-version-13.patch, dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace/0002-ast-Add-missing-standard-header-includes.patch, dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace_0.13.0.bb
=> bpftrace: Update to master

conf/layer.conf, dynamic-layers/browser-layer/recipes-browser/chromium-ozone-wayland_%.bbappend, dynamic-layers/browser-layer/recipes-browser/chromium-x11_%.bbappend, dynamic-layers/chromium-browser-layer/recipes-browser/chromium-ozone-wayland_%.bbappend, dynamic-layers/chromium-browser-layer/recipes-browser/chromium-x11_%.bbappend, dynamic-layers/chromium-browser-layer/recipes-browser/gn-native_%.bbappend
Fixes https://github.com/OSSystems/meta-browser/issues/560
=> Allow building meta-browser/master with meta-clang/gatesgarth

dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace/0001-support-clang-upto-version-13.patch, dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace/0002-orc-Fix-build-with-clang-13.patch, dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace_0.13.0.bb
=> bpftrace: Update to latest master

recipes-devtools/spirv-llvm-translator/spirv-llvm-translator_git.bb
Use latest revisions for SPIRV-LLVM-Translator and SPIRV-Headers
Signed-off-by: Zoltán Böszörményi <zboszor@gmail.com>
---
=> spirv-llvm-translator: Use latest revisions

recipes-devtools/castxml/castxml_git.bb, recipes-devtools/spirv-llvm-translator/spirv-llvm-translator_git.bb
---
- [ x] The PR complies with the [Open Embedded Commit Patch Message Guidelines](http://www.openembedded.org/wiki/Commit_Patch_Message_Guidelines) …
=> Fix warnings, add branch and use https when using github

dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc_0.17.0.bb, dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace_0.11.4.bb, recipes-devtools/castxml/castxml_git.bb
github has stopped supporting anonymous git protocol and bitbake now
warns about branch not being explicit, master is no more a viable
fallback
=> recipes: Specify branch and protocol in SRC_URI

recipes-devtools/clang/libcxx_git.bb
cmake 3.22+ is causing install failures e.g.
| -- Install configuration: "Debug"
| -- Installing: /mnt/b/yoe/master/build/tmp/work/armv7at2hf-neon-yoe-linux-gnueabi/libcxx/13.0.1-r0/image/usr/lib/libc++.so.1.0
| -- Installing: /mnt/b/yoe/master/build/tmp/work/armv7at2hf-neon-yoe-linux-gnueabi/libcxx/13.0.1-r0/image/usr/lib/libc++.so.1
| -- Set runtime path of "/mnt/b/yoe/master/build/tmp/work/armv7at2hf-neon-yoe-linux-gnueabi/libcxx/13.0.1-r0/image/usr/lib/libc++.so.1.0" to ""
| -- Installing: /mnt/b/yoe/master/build/tmp/work/armv7at2hf-neon-yoe-linux-gnueabi/libcxx/13.0.1-r0/image/usr/lib/libc++.so
| CMake Error at cmake_install.cmake:88 (file):
|   file RPATH_CHANGE could not write new RPATH:
|
|
|
|   to the file:
|
|     /mnt/b/yoe/master/build/tmp/work/armv7at2hf-neon-yoe-linux-gnueab …
=> libcxx: Set CMAKE_BUILD_WITH_INSTALL_RPATH

dynamic-layers/selinux/android-tools/android-tools_10.0.0.r36.bb
=> android-tools: Fix syntax overrides

conf/nonclangable.conf
=> php: Always use GCC for mips

conf/layer.conf, dynamic-layers/chromium-browser-layer/recipes-browser/chromium-ozone-wayland_%.bbappend, dynamic-layers/chromium-browser-layer/recipes-browser/chromium-x11_%.bbappend, dynamic-layers/chromium-browser-layer/recipes-browser/gn-native_%.bbappend
=> Dunfell clang12

.github/workflows/yoe.yml
This ensures that needed git operations on repos are intact.
---
=> gh-actions: Symlink meta-clang instead of copy

dynamic-layers/selinux/android-tools/android-tools_10.0.0.r36.bb
=> android-tools: Use SPDX license naming convention

classes/clang.bbclass, recipes-devtools/clang/llvm-project-source.inc
=> Fix multilib builds

classes/clang.bbclass, conf/nonclangable.conf, recipes-core/musl/musl_%.bbappend
=> ppc build fixes and usrmerge fixes

README.md
=> Add instructions for kernel build with clang

recipes-devtools/clang/clang_git.bb, recipes-devtools/clang/compiler-rt-sanitizers_git.bb, recipes-devtools/clang/compiler-rt_git.bb
=> clang: Fix native and nativesdk builds for hf targets

conf/nonclangable.conf
=> minio: Always use gnu strip utility

recipes-devtools/castxml/castxml_0.4.5.bb, recipes-devtools/clang/clang/0037-sanitizer-Remove-include-linux-fs.h-to-resolve-fscon.patch, recipes-devtools/clang/common.inc
=> sanitizer: Fix build with glibc 2.36

recipes-devtools/spirv-llvm-translator/spirv-llvm-translator_git.bb
---
- [ x] The PR complies with the [Open Embedded Commit Patch Message Guidelines](http://www.openembedded.org/wiki/Commit_Patch_Message_Guidelines)
=> spirv-llvm-translator: fix branch name

.github/workflows/yoe.yml
=> yoe.yml: Use poky repo to find sstate-cache-management.sh

recipes-graphics/mesa/mesa/0001-gallium-add-missing-header-for-powf.patch, recipes-graphics/mesa/mesa/0001-gallium-gallivm-remove-unused-header-include-for-newer-LLVM.patch, recipes-graphics/mesa/mesa/0001-gallivm-add-InstSimplify-pass.patch, recipes-graphics/mesa/mesa/0001-gallivm-fix-build-on-llvm-12-due-to-LLVMAddConstantPropagationPass-removal.patch, recipes-graphics/mesa/mesa_%.bbappend
Signed off: Florian Wühr <fwuehr@rational-online.com>
---
=> Mesa: Fix build due to newer LLVM version

dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc/0001-Vendor-just-enough-extra-headers-to-allow-libbpf-to-.patch, dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc_0.24.0.bb
Backport of https://github.com/kraj/meta-clang/pull/613
---
Cherry-picked without conflicts.
=> bcc: backport libbpf de-vendor fixes

recipes-devtools/clang/compiler-rt-sanitizers_git.bb
=> compiler-rt-sanitizer: fix nativesdk-compiler-rt-sanitizers build

conf/nonclangable.conf, recipes-devtools/python/python3_%.bbappend
=> Remove clang workarounds for several recipes from nonclangable.conf

conf/nonclangable.conf
=> remove more kludges

recipes-devtools/clang/clang_git.bb
Use libclang.so.* wildcard to include all .so files (not only dangling symlink ./usr/lib/libclang.so.15 -> libclang.so.15.0.1).
Fixes https://github.com/kraj/meta-clang/issues/658.
Before:
```
$ dpkg -c ./deploy/ipk/cortexa57/libclang_15.0.1-r0_cortexa57.ipk
drwxr-xr-x root/root         0 2011-04-06 01:00 ./usr/
drwxr-xr-x root/root         0 2011-04-06 01:00 ./usr/lib/
lrwxrwxrwx root/root         0 2011-04-06 01:00 ./usr/lib/libclang.so.15 -> libclang.so.15.0.1
```
After:
```
$ dpkg -c ./deploy/ipk/cortexa57/libclang15_15.0.1-r0_cortexa57.ipk
drwxr-xr-x root/root         0 2011-04-06 01:00 ./usr/
drwxr-xr-x root/root         0 2011-04-06 01:00 ./usr/lib/
lrwxrwxrwx root/root         0 2011-04-06 01:00 ./usr/lib/libclang.so.15 -> libclang.so.15.0.1
-rwxr-xr-x root/root  31291424 …
```
=> clang: Fix libclang package files list

README.md
Signed off: Florian Wühr [fwuehr@rational-online.com](mailto:fwuehr@rational-online.com)
---
=> Update Readme.md - fix typo

conf/nonclangable.conf
=> Fix kernel builds

recipes-devtools/clang/clang/0035-cmake-Enable-64bit-off_t-on-32bit-glibc-systems.patch
=> clang: Refresh off64_t musl patch

recipes-devtools/clang/clang/0036-compiler-rt-Undef-_TIME_BITS-along-with-_FILE_OFFSET.patch, recipes-devtools/clang/common.inc, recipes-devtools/clang/compiler-rt-sanitizers_git.bb
=> sanitizers: Fix build with 64bit time_t

conf/nonclangable.conf
=> Fix sysbench and mybw

recipes-devtools/clang/clang_git.bb
Signed-off-by: Chee Yang Lee <chee.yang.lee@intel.com>
---
=> clang: fix reproducible build

recipes-devtools/clang/compiler-rt-sanitizers_git.bb, recipes-devtools/clang/compiler-rt_git.bb, recipes-devtools/clang/libclc_git.bb, recipes-devtools/clang/libcxx_git.bb, recipes-devtools/clang/openmp_git.bb
=> compile clang runtime static libs as PIC

recipes-devtools/clang/clang_git.bb
backport 2 patch from master to fix reproducible build.
---
=> [langdale] clang: fix reproducible build

recipes-devtools/clang/clang_git.bb, recipes-devtools/clang/libcxx_git.bb
=> Make changes conducive for upcoming 16.x upgrade

classes/clang.bbclass
=> clang.bbclass: Replace mcpu with mtune

.github/workflows/yoe.yml
=> ci/actions: Adapt to new envsetup.sh syntax

dynamic-layers/selinux/android-tools/android-tools-conf_1.0.bb, dynamic-layers/selinux/android-tools/android-tools/libadb_mk_change_out_dir.patch, dynamic-layers/selinux/android-tools/android-tools/libbacktrace_mk_change_out_dir.patch, dynamic-layers/selinux/android-tools/android-tools/libbase_mk_change_out_dir.patch, dynamic-layers/selinux/android-tools/android-tools/libcrypto_mk_change_out_dir.patch, dynamic-layers/selinux/android-tools/android-tools/libcrypto_utils_mk_change_out_dir.patch, dynamic-layers/selinux/android-tools/android-tools/libcutils_mk_change_out_dir.patch, dynamic-layers/selinux/android-tools/android-tools/libext4_utils_mk_change_out_dir.patch, dynamic-layers/selinux/android-tools/android-tools/libfec_mk_change_out_dir.patch, dynamic-layers/selinux/android-tools/android-tools/liblog_mk_change_out_dir.patch, dynamic-layers/selinux/android-tools/android-tools/libsparse_mk_change_out_dir.patch, dynamic-layers/selinux/android-tools/android-tools/libunwind_mk_change_out_dir.patch, dynamic-layers/selinux/android-tools/android-tools/libziparchive_mk_change_out_dir.patch, dynamic-layers/selinux/android-tools/android-tools_10.0.0.r36.bb
=> Fix android-tools-native

dynamic-layers/selinux/android-tools/android-tools-conf_1.0.bb, dynamic-layers/selinux/android-tools/android-tools/libadb_mk_change_out_dir.patch, dynamic-layers/selinux/android-tools/android-tools/libbacktrace_mk_change_out_dir.patch, dynamic-layers/selinux/android-tools/android-tools/libbase_mk_change_out_dir.patch, dynamic-layers/selinux/android-tools/android-tools/libcrypto_mk_change_out_dir.patch, dynamic-layers/selinux/android-tools/android-tools/libcrypto_utils_mk_change_out_dir.patch, dynamic-layers/selinux/android-tools/android-tools/libcutils_mk_change_out_dir.patch, dynamic-layers/selinux/android-tools/android-tools/libext4_utils_mk_change_out_dir.patch, dynamic-layers/selinux/android-tools/android-tools/libfec_mk_change_out_dir.patch, dynamic-layers/selinux/android-tools/android-tools/liblog_mk_change_out_dir.patch, dynamic-layers/selinux/android-tools/android-tools/libsparse_mk_change_out_dir.patch, dynamic-layers/selinux/android-tools/android-tools/libunwind_mk_change_out_dir.patch, dynamic-layers/selinux/android-tools/android-tools/libziparchive_mk_change_out_dir.patch, dynamic-layers/selinux/android-tools/android-tools_10.0.0.r36.bb
=>  Fix android-tools-native (kirkstone backport)

dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc/0001-tests-cc-Use-c-14-standard.patch, dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc_0.26.0.bb, recipes-devtools/castxml/castxml_0.5.1.bb
=> Update bcc,castxml and spirv-llvm-translator to latest

dynamic-layers/selinux/android-tools/android-tools/adbd.mk, dynamic-layers/selinux/android-tools/android-tools/core/0009-patching-img2simg.mk-to-build-in-yocto-environment.patch, dynamic-layers/selinux/android-tools/android-tools/core/0010-patching-simg2img.mk-to-build-in-yocto-environment.patch, dynamic-layers/selinux/android-tools/android-tools/core/0016-Adapt-adbd-to-work-with-yocto.patch, dynamic-layers/selinux/android-tools/android-tools_10.0.0.r36.bb
=> Add adb daemon

recipes-devtools/clang/openmp_git.bb, recipes-graphics/mesa/mesa_%.bbappend
Some small layer cleanups to start with...
=> Layer cleanups (part 1)

conf/layer.conf, dynamic-layers/qt5-layer/recipes-qt/qt5/qtpdf_%.bbappend
=> Fix qtpdf with clang

classes/clang.bbclass, conf/layer.conf, dynamic-layers/qt6-layer/recipes-qt/qt6/qttools_%.bbappend, recipes-devtools/clang/clang.inc
See [1]
[1] https://codereview.qt-project.org/c/yocto/meta-qt6/+/476890
---
=> qt6/qttools: Fix build with clang

recipes-devtools/clang/clang/0037-Call-printName-to-get-name-of-Decl.patch
=> clang: Add missing SOB

dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc/0001-tests-cc-Use-c-14-standard.patch, dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc_0.28.0.bb
=> bcc: Upgrade to 0.28.0

conf/nonclangable.conf
=> babeltrace2: Ignore textrels with lld

classes/scan-build.bbclass
=> Fix clang-scan launch

classes/clang.bbclass
According to suggestions in #841 , backport:
- https://github.com/kraj/meta-clang/commit/6ecaea06d5e6e7ed0a39b4c019fc485f18e1ce55
- https://github.com/kraj/meta-clang/commit/7419c1f4e13187311870785a11e8cffee2c640e6
- https://github.com/kraj/meta-clang/commit/0f31c0b29580825af8700e484b984a8824a31a4f
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the …
=> Kirkstone backport ld is lld fixes

conf/nonclangable.conf
=> libfaketime: Add -Wl,--undefined-version with lld

classes/clang.bbclass
=> clang.bbclass: Simplify check when to enable lld

.github/workflows/yoe.yml
=> actions: Bump checkout for v3->v4

recipes-devtools/clang/openmp_git.bb
---
- [x ] Changes have been tested
- [x ] The PR complies with the [Open Embedded Commit Patch Message Guidelines](http://www.openembedded.org/wiki/Commit_Patch_Message_Guidelines) …
=> openmp: convert CVE_CHECK_IGNORE to CVE_STATUS

conf/nonclangable.conf
=> kernel-selftest: Fix build with lld and clang on x86

conf/nonclangable.conf
=> vboxguestdrivers: use gcc toolchain

conf/nonclangable.conf
They are not portable yet and assume gcc so give it to them
---
=> nonclangable: Add some tegra specific packages

.github/workflows/yoe.yml
=> yoe.yml: Use yoe_clean_sstate function from envsetup

conf/layer.conf
=> layer.conf: Update for the scarthgap release series

conf/nonclangable.conf
=> Fix wtmpdb and uftrace builds with clang

conf/layer.conf, recipes-devtools/clang/clang.inc
Brings
* c13b7485b879 [clang] Avoid -Wshadow warning when init-capture named same as class field (#74512)
* f249092ef26d [tsan] Refine fstat{,64} interceptors (#86625)
* 76c721994a11 [clang][Sema] Fix a CTAD regression after 42239d2e9 (#86914)
* e0f0c463b539 [mlir][transform] replace original op to loop ops (#83537)
* 47aac495c895 [OpenMP][AIX] Affinity implementation for AIX (#84984)
* a385a917da93 [Support] Fix color handling in formatted_raw_ostream (#86700)
* 0cd4babe0342 Reapply [libcxx] [modules] Fix relative paths with absolute LIBCXX_INSTALL_MODULES_DIR (#86020)
* cfaeee6a8994  release/18.x: [SystemZ] Fix overflow flag for i128 USUBO (#86491)
* 767b61c159b3 [lld/ELF][X86] Respect outSecOff when checking if GOTPCREL can be relaxed (#86334)
* 7c7c3d4a3a27 [ODS][NFC] Cast …
=> clang: Upgrade to 18.1.3

dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace/0001-use-64bit-alignment-for-map-counter-atomic-add.patch, dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace/run-ptest, dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace_0.20.1.bb
=> fix bpftrace runtime error

conf/layer.conf, recipes-devtools/clang/clang.inc
* e6c3289804a6 [CMake][Release] Disable PGO (#88465) (#89000)
* 028e425f86cc [MIPS] Fix the opcode of max.fmt and mina.fmt (#85609)
* e3c832b37b0a Fix override keyword being print to the left side
* 1deeee3f5da4 Revert "[Mips] Fix missing sign extension in expansion of sub-word atomic max (#77072)"
* 995539ce05ba [LLD] [COFF] Don't add pseudo relocs for dangling references (#88487)
* db67e6fb9ad1 [libc++] Fix -Wgnu-include-next in stddef.h (#88214)
* 647fbc710840 [SelectionDAG] Prevent combination on inconsistent type in `combineCarryDiamond` (#84888)
* eaae766a20fd [RISCV] Support rv{32, 64}e in the compiler builtins (#88252)
* c24b41d71f2e github-upload-release.py: Fix bug preventing release creation (#84571)
* c837970dd7e9 [Codegen][X86] Fix /HOTPATCH with clang-cl and inline asm …
=> clang: Upgrade to 18.1.4

README.md, recipes-devtools/clang/common-source.inc, recipes-devtools/clang/common.inc, recipes-devtools/clang/libcxx_git.bb, recipes-devtools/clang/llvm-project-source.inc, recipes-devtools/clang/nativesdk-clang-glue.bb, recipes-devtools/spirv-llvm-translator/spirv-llvm-translator_git.bb, scripts/devtool-clang.sh
=> Fix archiver for llvm-source and improve working with devtool 

dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace_0.20.1.bb, recipes-devtools/clang/libclc_git.bb, recipes-devtools/spirv-llvm-translator/spirv-llvm-translator_git.bb
=> Fix libclc and drop LLVMVERSION

recipes-devtools/clang/libclc_git.bb
cmake complains otherwise
toolchain incomplete!
---
=> libclc: Add toolchain component paths

conf/layer.conf, conf/nonclangable.conf
=> layer.conf: Update to walnascar (5.2) layer/release series

conf/layer.conf, recipes-devtools/clang/clang.inc, recipes-devtools/clang/common.inc
Release has changes as mentioned in [1] and [2]
[1] https://discourse.llvm.org/t/llvm-19-1-1-released/82321
[2] https://discourse.llvm.org/t/llvm-19-1-2-released/82550
---
=> clang: Upgrade to 19.1.2 release

recipes-devtools/clang/clang_git.bb
Backport fix for #1022 to Styhead
=> clang_git.bb: assign PYTHON_PN to LLDB_PYTHON_EXE_RELATIVE_PATH

conf/layer.conf, recipes-devtools/clang/clang.inc, recipes-devtools/clang/common.inc
Brings following changes [1]
[1] https://github.com/llvm/llvm-project/compare/llvmorg-19.1.5...llvmorg-19.1.6
---
=> clang: Upgrade to 19.1.6

recipes-devtools/bindgen-cli/bindgen-cli-crates.inc, recipes-devtools/bindgen-cli/bindgen-cli_0.71.1.bb
Related to some issues in my project with compiling aws-lc-rs, issue https://github.com/aws/aws-lc-rs/issues/591, I updated to the current version.
Tested on my project
https://github.com/MrTarantoga/SpotyPee/commit/f83b2a0c32f28af2c81069ced5b9942bbb98d25a and with the poky standard arm environment.
Changelog https://github.com/rust-lang/rust-bindgen/releases/tag/v0.71.1
---
- '*Comment*' if you don't feel you have enough information to decide …
=> bingen-cli: Upgrade to 0.71.1

recipes-devtools/clang/clang_git.bb
Currently, class-target is reproducible, but
class-nativesdk is not. What I did:
- noticed that BuildVariables.inc contains meaningless path fragments after running sed, so I adjusted sed commands to remove the rest of paths as well;
- moved common code into a function, which is then called twice;
- changed do_compile:prepend into do_configure:append, this is more conventional and intuitive;
- verified that the resulting code works for both target and nativesdk after these changes.
Fixes:
```
ERROR: nativesdk-clang-18.1.6-r0 do_package_qa: QA Issue: File /usr/local/oe-sdk-hardcoded-buildpath/sysroots/x86_64-oesdk-linux/usr/bin/llvm-config in package nativesdk-clang contains reference to TMPDIR [buildpaths]
```
```
$ strings BUILD/work/x86_64-nativesdk-oesdk-linux/nativesdk-clang/18.1.6/pac …
```
=> clang: improve reproducibility

conf/layer.conf, conf/nonclangable.conf, recipes-devtools/clang/clang.inc, recipes-devtools/clang/common.inc
=> Upgrade Clang to 19.1.7

conf/nonclangable.conf
=> Fixes with glibc 2.41

dynamic-layers/selinux/android-tools/android-tools/core/0009-patching-img2simg.mk-to-build-in-yocto-environment.patch, dynamic-layers/selinux/android-tools/android-tools/core/0010-patching-simg2img.mk-to-build-in-yocto-environment.patch, dynamic-layers/selinux/android-tools/android-tools_10.0.0.r36.bb
=> android-tools: Implement usage of img2simg and simg2img

conf/nonclangable.conf
LLD fails to link mesa 25.x sadly
| Error relocating riscv32-yoe-linux-musl/gstreamer1.0-plugins-base/1.26.0/recipe-sysroot//usr/lib/libGLESv2.so.2: unsupported relocation type 12
| Error relocating riscv32-yoe-linux-musl/gstreamer1.0-plugins-base/1.26.0/recipe-sysroot//usr/lib/libGL.so.1: unsupported relocation type 12
| Error relocating riscv32-yoe-linux-musl/gstreamer1.0-plugins-base/1.26.0/recipe-sysroot//usr/lib/libGL.so.1: unsupported relocation type 12
| Error relocating riscv32-yoe-linux-musl/gstreamer1.0-plugins-base/1.26.0/recipe-sysroot//usr/lib/libEGL.so.1: unsupported relocation type 12
| Error relocating riscv32-yoe-linux-musl/gstreamer1.0-plugins-base/1.26.0/recipe-sysroot//usr/lib/libEGL.so.1: unsupported relocation type 12
| Error relocating …
=> mesa: Fall back to use BFD linker on riscv32

dynamic-layers/meta-python/recipes-devtools/bcc/bcc/bpf_stack_id.patch, dynamic-layers/meta-python/recipes-devtools/bcc/bcc_0.33.0.bb
=> Fix for a few bcc ptest issues 

classes/clang.bbclass, conf/nonclangable.conf
=> Use gcc for vulkan-samples and disable lld on ppc32

classes/clang-legacy.bbclass
=> Cleanup after clang merge to core.

classes/clang-legacy.bbclass, conf/nonclangable.conf, recipes-multimedia/libvorbis/libvorbis_%.bbappend, recipes-support/libunwind/libunwind_%.bbappend
=> Sync with changes migrated to core layer

.github/workflows/yoe.yml
environment has the paths to it.
---
=> ci: Remove paths for sstate-cache-management.py
