- recipes-support/rng-tools/rng-tools/When-adding-entropy-allocate-the-struct-dynamically.patch
- recipes-support/rng-tools/rng-tools_5.bbappend
This fixes 'error: fields must have a constant size' by allocating it with the
given buffer size dynamically.
> rng-tools: fix build with clang

- recipes-devtools/clang/clang/0001-Frontend-support-I-path-for-sysroot-expansion.patch
- recipes-devtools/clang/clang_git.bb
This solves some clang issues. A few recipes rely on gcc's
-I=<include directory> syntax. This is a backport of the feature to the 3.8
branch. It's already in 3.9.
See https://llvm.org/bugs/show_bug.cgi?id=26965
> clang: backport -I= support

- recipes-devtools/clang/clang_git.bb
Otherwise llvm-tblgen cannot be found if clang happens
to be built before clang-native.
Signed-off-by: Dmitry Rozhkov <dmitry.rozhkov@linux.intel.com>
> clang_git.bb: Add dep on clang-native to clang

- recipes-devtools/clang/clang_git.bb
This commit cherry-picks bf0a01851fb7cd8d66a23cef0f69df519c085eff
from master to krogoth.
TUNE_CCARGS is an SSTATE variable and it must not used so that
it becomes builder specific. Builder specific TUNE_CCARGS makes
the SSTATE checksums to change and it invalidates the SSTATE cache
if used via SSTATE_MIRROR.
I've tested it builds with Ostro OS XT.
Fixes: #24
> backport: clang-3.9: Remove unneeded flags for target

- recipes-devtools/clang/clang_git.bb
With the layer defaults (TOOLCHAIN ??= gcc) clang for target fails
to build due to missing compilers in the native (recipe specific)
sysroot.
Set the necessary additional DEPENDS if TOOLCHAIN = gcc to get the
compilers installed.
Signed-off-by: Mikko Ylinen <mikko.ylinen@linux.intel.com>
> clang: set target DEPENDS for gcc TOOLCHAIN

- recipes-devtools/clang/clang.inc
- recipes-devtools/clang/clang/0004-llvm-allow-env-override-of-exe-path.patch
- recipes-devtools/clang/clang_git.bb
- recipes-devtools/clang/compiler-rt_git.bb
- recipes-devtools/clang/llvm-common/llvm-config
Hi,
This patch series fixes a number of issues I hit when trying to use the
meta-clang llvm-config to cross-compile a project that uses CMake, calling
into llvm-config, to determine compile flags. With the series applied, the
cross compile successfully builds and runs. Please let me know if you have
any concerns or if there is something I missed, and I will fix it up.
> llvm config fixes

- recipes-devtools/clang/clang_git.bb
`binutils` is not needed during compile time. Add it instead to `RRECOMMENDS_clang`.
> Remove binutils from DEPENDS

- recipes-devtools/clang/clang_git.bb
Fixes:
ERROR: clang-5.0.0+gitAUTOINC+f65227fd46_2ce35b601d-r0 do_package: QA Issue: clang: Files/directories were installed but not shipped in any package:
/usr/share/opt-viewer
/usr/share/opt-viewer/optrecord.py
/usr/share/opt-viewer/opt-viewer.py
/usr/share/opt-viewer/opt-stats.py
/usr/share/opt-viewer/optpmap.py
/usr/share/opt-viewer/opt-diff.py
/usr/share/opt-viewer/style.css
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
Signed-off-by: Ricardo Ribalda Delgado <ricardo.ribalda@gmail.com>
> clang: Add missing FILE

- recipes-devtools/clang/clang_git.bb
Without this, we get a syntax error when we don't override
LLVM_TARGETS_TO_BUILD_TARGET because LLVM_TARGETS_TO_BUILD_TARGET gets
set as something like "X86X86" instead of "X86;X86".
Signed-off-by: Martin Kelly <mkelly@xevo.com>
> clang: add missing ; for llvm targets

- recipes-devtools/clang/clang_git.bb
Signed-off-by: Daniel Díaz <daniel.diaz@linaro.org>
> clang: enable support for BPF target

- recipes-devtools/clang/clang_git.bb
llvm-config is, by default, broken by the SSTATE_SCAN_CMD. This patch
removes llvm-config from SSTATE_SCAN_FILES.
Signed-off-by: Ricardo Ribalda Delgado <ricardo.ribalda@gmail.com>
> clang: Fix sigsegv of llvm-config on the target

- recipes-devtools/clang/compiler-rt/0005-sanitizer-Use-pre-computed-size-of-struct-ustat-for-.patch
- recipes-devtools/clang/compiler-rt_git.bb
<sys/ustat.h> has been removed from glibc 2.28 by:
commit cf2478d53ad7071e84c724a986b56fe17f4f4ca7
author: Adhemerval Zanella <adhemerval.zanella@linaro.org>
Date: Sun Mar 18 11:28:59 2018 +0800
Deprecate ustat syscall interface
This patch uses pre-computed size of struct ustat for Linux to fix
https://bugs.llvm.org/show_bug.cgi?id=37418
Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
> compiler-rt: Use pre-computed size of struct ustat for Linux

- recipes-devtools/clang/clang-cross-canadian_git.bb
- recipes-devtools/clang/clang-crosssdk_git.bb
No longer required see,
http://git.openembedded.org/openembedded-core/commit/?id=122217b421f749b5fef52bea44ad6e04bc8f8d3a
Signed-off-by: Aníbal Limón <anibal.limon@linaro.org>
> recipes-devtools/clang: Drop virtual/libc-for-gcc

- recipes-devtools/clang/clang.inc
- recipes-devtools/clang/common.inc
- recipes-devtools/clang/llvm-project-source.bb
LLVM has set up an official git monorepo. Switch to that, and use its branch naming scheme.
> Switch to canonical git mirror

- recipes-devtools/clang/clang.inc
- recipes-devtools/clang/clang/0016-clang-Append-libunwind-to-compiler-rt-for-linking.patch
- recipes-devtools/clang/common.inc
- recipes-devtools/clang/compiler-rt_git.bb
- recipes-devtools/clang/libcxx_git.bb
Bolt in fixes for building with compiler-rt + libcxx instead of libgcc + libstdc++
> Update clang to latest 8.x

- recipes-devtools/clang/clang/0016-clang-Append-libunwind-to-compiler-rt-for-linking.patch
compiler-rt is not a full replacement for libgcc, it provides the
built-ins so we are left with EH and unwinding support to be had from
elsewhere, we could use LLVM linunwind but that depends on libpthread
so it will end up pulling too many libraries for meantime link with
libgcc_eh.a when --rtlib=compiler-rt
> clang: link with libgcc_eh.a when using compiler-rt

- recipes-connectivity/samba/files/fix_duplicate_pdb_search_init.patch
- recipes-connectivity/samba/samba_4.8.%.bbappend
- recipes-graphics/wayland/files/fix_duplicate_main.patch
- recipes-graphics/wayland/wayland_1.16.%.bbappend
Samba: https://svnweb.freebsd.org/ports/branches/2018Q4/net/samba47/files/patch-source3__wscript_build?view=markup&pathrev=481551
Wayland: https://gitlab.freedesktop.org/wayland/wayland/commit/c70fd8a812d74b5ef6fcba1287b409f4f8821e91
> Fix duplicates symbols when building with lld

- recipes-devtools/clang/clang_git.bb
Allows building llvm/clang on Centos7 (gcc4.8) which still is one of the
suported distros in YP.
Signed-off-by: Anuj Mittal <anuj.mittal@intel.com>
> clang: support old toolchains

- recipes-devtools/clang/clang_git.bb
This ensures that right default target is used and one does not need
to specify it manually using -target option or -mfloat-abi when using on
target
> clang: Add hf to target tuple if hard float calling convention is used

- recipes-devtools/clang/lldb_git.bb
lldb doesn't build when -Wformat-security -Werror=format-security is
added/enabled and results in errors with gcc9:
| BUILD/build/tmp/work-shared/llvm-project-source-8.0.1-r0/git/lldb/source/Core/Module.cpp: In member function 'size_t lldb_private::Module::FindTypes_Impl(const lldb_private::ConstString&, const lldb_private::CompilerDeclContext*, bool, size_t, llvm::DenseSet<lldb_private::SymbolFile*>&, lldb_private::TypeMap&)':
| BUILD/build/tmp/work-shared/llvm-project-source-8.0.1-r0/git/lldb/source/Core/Module.cpp:951:52: error: format not a string literal and no format arguments [-Werror=format-security]
|   951 |   Timer scoped_timer(func_cat, LLVM_PRETTY_FUNCTION);
|       |                                                    ^
| …
> lldb: ignore format-security warnings

- recipes-devtools/clang/clang_git.bb
This library has a few potential consimers (ex, qttools) which don't
need whole clang install. Distributions like debian already package
lbiclang separately as libclang1. This makes even more sense for
embedded systems. Do the same for OE/Yocto.
Signed-off-by: Piotr Tworek <tworaz@tworaz.net>
> clang: Move libclang into its own dedicated package.

- recipes-devtools/clang/clang_git.bb
Some cmake based steps when building clang uses BUILD_CC, BUILD_CXX variables,
which points to gcc even if `TOOLCHAIN_class-nativesdk = "clang"`.
This patch sets it to clang if `TOOLCHAIN_class-nativesdk = "clang"` is set.
Signed-off-by: Daniel Dittmann <daniel.dittmann@rohde-schwarz.com>
> use native-clang compiler when building nativesdk-clang

- conf/nonclangable.conf
The package was recently updated to version 0.60.7 which builds fine
with both clang 8.x and 9.x.
Signed-off-by: Piotr Tworek <tworaz@tworaz.net>
> nonclangable: Remove aspell from the list

- recipes-devtools/clang/clang_git.bb
Without this for some reason lldb configure process manages to mix host
system provided python3 interpreter with libpython provided in
recipe-sysroot-native. As result the build fails with the following
error message:
| -- Found PythonInterp: /usr/bin/python3.6 (found version "3.6.5")
...
| -- Found PythonLibs: /mnt/storage/build-purple/tmp-musl/work/x86_64-linux/clang-native/9.0.0-r0/recipe-sysroot-native/usr/lib/libpython3.7m.so (found version "3.7.4")
| CMake Error at /mnt/storage/build-purple/tmp-musl/work-shared/llvm-project-source-9.0.0-r0/git/lldb/cmake/modules/LLDBConfig.cmake:204 (message):
|   Found incompatible Python interpreter (3.6.5) and Python libraries (3.7.4)
| Call Stack (most recent call first):
|   /mnt/storage/build-purple/tmp-musl/work-shared/llvm-project-source-9.0. …
> clang: Inherit python3native.

- recipes-devtools/clang/clang_git.bb
Even when inheriting Python3native, CMake is picking up the system python executable for some reason, and can cause builds to fail. This fixes that by explicitly providing the path to the executable for CMake to use.
Resolves #145
> Pass Python3 Exectuable to CMake

- recipes-devtools/clang/libcxx_git.bb
Without this bitbake will still pull standard libunwind package when
building recipes depending on libunwind. If such recipe also happens
to pull libcxx the build will fail when assembling the sysroot because
both libcxx and libunwind provide libunwind.so.
This problem has been observed when building libstd-rs from meta-rust
layer agains musl libc.
Signed-off-by: Piotr Tworek <tworaz@tworaz.net>
> libcxx: Add libunwind to PROVIDES not only RPROVIDES.

- conf/layer.conf
can't build with sumo because of the dependency on libedit which require native.
libedit doesn't provide BBCLASSEXTEND on sumo.
> layer: drop sumo support

- classes/clang.bbclass
- recipes-core/musl/musl_%.bbappend
- recipes-devtools/clang/clang.inc
- recipes-devtools/clang/common.inc
- recipes-devtools/clang/compiler-rt_git.bb
- recipes-devtools/clang/libcxx_git.bb
Default to ssp and pie irrespective of GCCPIE
this lets us build one clang for all
> clang: Upgrade to latest 9.x

- recipes-devtools/clang/clang_git.bb
Fixes:
| install: cannot stat ‘/data/dwrobel1/onemw/onemw/oe-builds/chromium-3/onemw/build-brcm97449svms-refboard/tmp/work/x86_64-linux/clang-native/9.0.0-r0/build/bin/clang-tblgen’: No such file or directory
| WARNING: /data/dwrobel1/onemw/onemw/oe-builds/chromium-3/onemw/build-brcm97449svms-refboard/tmp/work/x86_64-linux/clang-native/9.0.0-r0/temp/run.do_install.25108:1 exit 1 from 'install -Dm 0755 /data/dwrobel1/onemw/onemw/oe-builds/chromium-3/onemw/build-brcm97449svms-refboard/tmp/work/x86_64-linux/clang-native/9.0.0-r0/build/bin/clang-tblgen /data/dwrobel1/onemw/onemw/oe-builds/chromium-3/onemw/build-brcm97449svms-refboard/tmp/work/x86_64-linux/clang-native/9.0.0-r0/image/data/dwrobel1/onemw/onemw/oe-builds/chromium-3/onemw/build-brcm97449svms-refboard/tmp/sysroots/x86_64-linux/usr/ …
> Fix installation of clang-tblgen and lldb-tblgen

- recipes-devtools/clang/clang/0001-Pass-PYTHON_EXECUTABLE-when-cross-compiling-for-nati.patch
- recipes-devtools/clang/clang_git.bb
- recipes-devtools/clang/common.inc
- recipes-devtools/clang/compiler-rt_git.bb
- recipes-devtools/clang/libcxx_git.bb
This makes sure that correct Python (python3native) is detected when compiling target clang and that we're able to compile when multilib is enabled.
> fixes for multilib and python detection

- classes/clang.bbclass
The variable is expected in some code usages as having some
content. With an empty variable, sed fails in some locations.
sed 's,,,g'
sed: -e expression #1, char 0: no previous regular expression
Also since clang can be included an not used the variable
should only be set when the toolchain setting is clang.
Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>
> clang.bbclass: Add clang override ad space in DEBUG_PREFIX_MAP

- conf/nonclangable.conf
They do static linking, and when linking with glibc it expects
intrinsics from libgcc since we do not use clang to build glibc
this is not an issue on musl since we use clang to build most of
musl ports
> nonclangable: Use libgcc for libc-bench, aufs-util, libhugetlbfs, tsocks

- conf/layer.conf
- recipes-devtools/clang/clang_git.bb
- recipes-graphics/mesa/mesa_%.bbappend
When using meta-clang, it makes sense to use llvm provided by clang
recipe, this ensures that we do not build llvm from oe-core but instead
offer the one from clang recipe
enable rtti and eh for native/nativesdk clang, this is needed for mesa
to build
Let clang PROVIDE llvm
Build AMDGNU and other targets, this is needed for llvm-config to work
properly, since we use llvm-config from clang-native, so its better to
build the targets that are built for clang-native atleast
create version specific symlinks for tblgen anf llvm-config
> clang: Provide llvm/llvm-native

- recipes-devtools/clang/clang_git.bb
Allows libedit to dependency to be disabled via
PACKAGECONFIG_remove.
add libedit to native and nativesdk packageconfigs
Signed-off-by: Yong, Jonathan <jonathan.yong@intel.com>
> clang: make libedit optional

- recipes-devtools/clang/clang_git.bb
clang might be used for more than just static compiler on target and
therefore lock-stepping it with needing clang cross-compiler is not
right thing
> clang: Do not lock clang as only cross compiler option

- conf/nonclangable.conf
gcc uses intrinsics for atomic<double> but clang does not for x86
when using libstdc++
./media/audio/pulse/pulse_input.cc uses this atomic variable
> qtwebengine: Link libatomic on x86/clang/gnu-runtime

- recipes-devtools/clang/clang/0021-Check-for-atomic-double-intrinsics.patch
- recipes-devtools/clang/common.inc
This helps in deciding on linking libatomic, therefore its important to
check for atomic<double> because on x86, clang decides to not use
built-in whereas gcc does, so clangd e.g. links ok when using gcc but
fails when using clang with gcc-runtime on x86
Backport of ba6e545b1d0ee93b4ef698fae2d5a018a062b46a
Signed-off-by: Michael Davis <michael.davis@essvote.com>
> llvm: Check for built-in atomic<double> during configure

- recipes-devtools/clang/clang_git.bb
In 003dd05e4c168f7c3cccb9cbfad3fd8f38fe8741, clang replaced the oe-core
provided llvm for building mesa.  However, mesa needs AMDGPU to be
enabled on the native target in order to build.  Following the example
of oe-core's recipe, just enable AMDGPU for all targets.
Signed-off-by: Justin Bronder <jsbronder@cold-front.org>
> clang: enable AMDGPU for all targets

- recipes-core/packagegroups/nativesdk-packagegroup-sdk-host.bbappend
- recipes-core/packagegroups/packagegroup-core-standalone-sdk-target.bbappend
As CLANGSDK defaults to '1', users who have not read the README may
think that setting it to '0' would disable adding Clang to the SDK.
Little do they know that you need to *unset* the value for this to work
(as bool('0') -> True).
Change the logic to use bb.utils.contains(), so that '0' is not true.
Signed-off-by: Ross Burton <ross.burton@intel.com>
> packagegroup: be lenient about CLANGSDK setting

- recipes-devtools/clang/clang_git.bb
This fixes #162 for nativesdk-clang.
> clang: ensure correct python for nativesdk builds

- recipes-devtools/clang/clang/0026-libclang-Use-CMAKE_DL_LIBS-for-deducing-libdl.patch
- recipes-devtools/clang/common.inc
This ensures that clang can link with libdl on platforms where needed
Fixes issue #241
> clang: Use cmake variable for libdl

- conf/nonclangable.conf
> hdf5: Use gcc on musl/x86_64

- conf/nonclangable.conf
Fails with error on clang
error: return address can be determined only for current frame
> libexecinfo,openflow: Use gcc on mips

- recipes-devtools/clang/clang.inc
- recipes-devtools/clang/compiler-rt_git.bb
- recipes-devtools/clang/libcxx_git.bb
Our Yocto SDK is not compatible for zeus/master.
I created a PR for warrior branch.
But this PR is not still full covered for #247 issue.
This PR prevents QA error on multiarch environment.
Co-authored-by: INAJIMA Daisuke <inajima@soum.co.jp>
> Support multiarch Yocto environment on warrior

- conf/nonclangable.conf
Fixes
/usr/src/debug/cpio/2.13-r0/build/gnu/../../cpio-2.13/gnu/xmalloc.c:100: undefined reference to `__mulodi4'
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:1124: recipe for target 'rmt' failed
> cpio: Link with compiler-rt when using clang

- recipes-devtools/clang/clang.inc
- recipes-devtools/clang/compiler-rt_git.bb
- recipes-devtools/clang/libcxx_git.bb
This PR is uplift to master branch for #251.
Tested on raspberry3-64 multiarch image on Yocto master with the following additional config:
```
require conf/multilib.conf
MULTILIBS = "multilib:lib32"
DEFAULTTUNE_virtclass-multilib-lib32 = "armv7athf-neon
```
> Compute llvm libdir suffix on multiarch

- recipes-devtools/clang/openmp_git.bb
Fixes
error Unknown or unsupported architecture
> openmp: Mark mips64 unsupported host

- recipes-devtools/clang/clang_git.bb
Signed-off-by: Michael Davis <michael.davis@essvote.com>
> clang: Fix cmake exports sed variable using incorrect name

- conf/nonclangable.conf
This helps configure scripts to detect right set of
compiler specific options to enable
> nfs-utils: Enable unknown-warnings as errors

- recipes-devtools/clang/clang_git.bb
src uri has long moved to git, and that is also being used as solib suffix
Fixes packaging errors
ERROR: clang-10.0.0-r0 do_package_qa: QA Issue: libclang rdepends on clang-dev [dev-deps]
ERROR: clang-10.0.0-r0 do_package_qa: QA Issue: clang rdepends on clang-dev [dev-deps]
> clang: Use git suffix instead of svn

- conf/nonclangable.conf
gobject-intospection and avahi do not yet prelink with clang/mips64
> mesa: Clang can compile it on mips

- recipes-devtools/clang/clang/0028-Add-libgcc-to-link-step-for-libcxx.patch
- recipes-devtools/clang/common.inc
Add libgcc as defined by $CC to link of libc++.
Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>
> libcxx: Correct link failure due to missing __divti3

- recipes-devtools/clang/clang.inc
An earlier commit added a suffix table to determine the libdir suffix
for multilib targets. This table failed at least in the lib32 case for
x86, where the suffix should have been '', but was instead '32'.
Use the same method as the cmake bbclass instead.
Signed-off-by: Daniel McGregor <daniel.mcgregor@vecima.com>
> Use simplier libdir suffix computation

- recipes-gnome/gcr/gcr_%.bbappend
QEMU crash has fixed itself overtime now.
> gcr: Do not disable gobject-introspection

- recipes-devtools/clang/clang/0029-clang-llvm-cmake-Fix-configure-for-packages-using-fi.patch
- recipes-devtools/clang/common.inc
Currently, when a package (i.e. bcc [https://github.com/iovisor/bcc.git])
that depends on LLVM tries to run find_package(LLVM) during do_configure,
it will fail with the following error:
|   The imported target "llvm-tblgen" references the file
|      ".../recipe-sysroot/usr/bin/llvm-tblgen"
|
|   but this file does not exist.  Possible reasons include:
|   * The file was deleted, renamed, or moved to another location.
|   * An install or uninstall procedure did not complete successfully.
|   * The installation package was faulty and contained
|      ".../recipe-sysroot/usr/lib/cmake/LLVMExports.cmake"
|   but not all the files it references.
This is due to the fact that LLVM target binaries will not be present in the
sysroot, only the libraries will. Work around this by not exporting the …
> clang,llvm: cmake: Fix configure for packages using find_package() 

- recipes-devtools/bcc/bcc/0001-Allow-to-build-with-OE-LLVM-cross-compiled-package.patch
- recipes-devtools/bcc/bcc/0001-BCC-Use-python-3.patch
- recipes-devtools/bcc/bcc_0.12.0.bb
- recipes-devtools/bpftrace/bpftrace/0001-Allow-to-build-with-OE-llvm-clang-cross-compiled-pac.patch
- recipes-devtools/bpftrace/bpftrace_0.9.4.bb
Since eBPF tool relies on Clang to build eBPF bytecode, this patch set tries to enable the two tools BCC and bpftrace into meta-clang layer.  BCC is dependent on an extra luajit patch for upgrading to 2.1.0-meta3 [1].
This patch set has been tested with qemux86 and qemuarm64.
[1] http://lists.openembedded.org/pipermail/openembedded-devel/2020-February/205070.html
> Support eBPF tools in meta-clang layer

- recipes-devtools/bcc/bcc/0001-Allow-to-build-with-OE-LLVM-cross-compiled-package.patch
- recipes-devtools/bcc/bcc/0001-BCC-Use-python-3.patch
- recipes-devtools/bcc/bcc_0.13.0.bb
Since Clang has been upgraded to 10.0.0, it leads to BCC building
failure which is caused by LLVM functions definition mismatching.
This patch upgrades BCC to v0.13.0 so can support Clang 10.0.0.
Signed-off-by: Leo Yan <leo.yan@linaro.org>
> BCC: Upgrade to v0.13.0

- conf/nonclangable.conf
Building mesa (at least version 19.3.4) with clang 9.0.1 leads
to linker errors on x86/x86-64:
"undefined reference to `typeinfo for llvm::raw_pwrite_stream'"
in libvulkan_radeon.so
and
"undefined reference to `typeinfo for llvm::RTDyldMemoryManager'"
in libgallium.a.
It was reported at https://gitlab.freedesktop.org/mesa/mesa/issues/2533
It seems it is related to rtti not being enabled, at least reports
from a few years ago on forums lead to that conclusion.
But enabling rtti for clang in PACKAGECONFIG doesn't help.
Just build mesa with gcc, it fixes the linker errors.
Signed-off-by: Böszörményi Zoltán <zboszor@pr.hu>
> [zeus] conf/nonclangable.conf: Always build mesa with gcc

- conf/nonclangable.conf
.S files use GNU syntax which does not work with integrated asm
> libde265: Do not use internal assembler on arm

- recipes-devtools/bcc/bcc_0.13.0.bb
- recipes-devtools/bpftrace/bpftrace_0.9.4.bb
bcc:
* use gitsm fetcher to make sure src/cc/libbpf submodule is always present
* Fix do_package QA errors when baselib=lib64
bpftrace:
* Disable building unit tests
* Add dependency on gzip-native
> bcc, bpftrace fixes

- conf/nonclangable.conf
meson logic in pipewire uses compiler cmdline to find if SSE is
supported or not but if we use -Wno-error=unused-command-line-argument
then the error is turned into warning and tests pass even on non-x86
machines which is not correct
> pipewire: Do no mis-detect SSE support

- classes/clang.bbclass
- conf/nonclangable.conf
This option can turn Valid options into warnings and cause unintended
behaviour
> recipes: Do not Add -Wno-error=unused-command-line-argument globally

- recipes-devtools/clang/openmp_git.bb
Add missing rdeps on libelf and libffi
> openmp: Fix build packaging with multilib suffix

- recipes-devtools/clang/clang/0023-clang-Fix-resource-dir-location-for-cross-toolchains.patch
- recipes-devtools/clang/common.inc
By default, clang looks for resourses relative to the binary location:
${location}/../lib/clang/${version}/
However, the default bindir defined in cross.bbclass is a subdirectory of bin,
so clang forms a directory that looks like /usr/bin/lib/clang/10.0.0/
Apply a patch to use ${location}/../../lib/clang/${version} if the directory
name of ${location}/.. is "bin".
Signed-off-by: Jim Broadus <jbroadus@xevo.com>
> clang: Fix default resources directory when cross compiling

- conf/nonclangable.conf
it seems to not use unified syntax
> libsdl2: Do not use internal asm

- recipes-devtools/clang/clang/0024-fix-path-to-libffi.patch
- recipes-devtools/clang/common.inc
Don't use the full path to libffi and avoid linking to the one
from clang's sysroot. Prevents errors like:
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: VERBOSE=1 cmake --build /build/build/tmp/work/corei7-64-poky-linux/opencl-clang/10.0.0-r0/build --target all --
| ninja: error: '/build/build/tmp/work/corei7-64-poky-linux/clang/10.0.0-r0/recipe-sysroot/usr/lib/libffi.so', needed by 'libopencl-clang.so.10', missing and no known rule to make it
| WARNING: exit code 1 from a shell command.
| ERROR: Execution of '/build/build/tmp/work/corei7-64-poky-linux/opencl-clang/10.0.0-r0/temp/run.do_compile.72389' failed with exit code 1:
| ninja: error: '/build/build/tmp/work/corei7-64-poky-linux/clang/10.0.0-r0/recipe-sysroot/usr/lib/libffi.so', needed by …
> fix build errors when using libLLVMInterpreter

- classes/clang.bbclass
Clang does not yet support big.LITTLE performance tunes, so use the LITTLE for tunes
see [1]
Fixes Issue #313
[1] https://reviews.llvm.org/D32076
> clang.bbclass: Handle big.LITTLE mtune options on arm/aarch64

- recipes-devtools/clang/clang_git.bb
With lldb split in multiple packages it reduces the size of the `clang` 
package and you can now install lldb, lldb-server and liblldb without h
having the whole clang fat package.
> clang: add lldb, lldb-server, liblldb packages

- conf/layer.conf
bcc is only compatible with x86_64, aarch64 and powerpc64. So it's not able to
built as 32 bit binary.
Signed-off-by: He Zhe <zhe.he@windriver.com>
> layer.conf: Add bcc to non-multilib list

- recipes-devtools/clang/openmp_git.bb
Needs libffi and libelf as dependencies, and is available only for
aarch64/x86_64/ppc64
> openmp: Make offloading-plugin as packageconfig

- classes/clang.bbclass
- classes/cmake-native.bbclass
It fails to build compiler-rt when ccache enabled:
| ccache: error: Failure running compiler check command: %compiler% -dumpspecs
Because clang doesn't recognize option '-dumpspecs' from default value
of CCACHE_COMPILERCHECK, override CCACHE_COMPILERCHECK for toolchain
clang in clang.bbclass.
And it reset variable CCACHE to disable ccache in cmake-native.bbclass:. But that doesn't effect that  CCACHE is set in an anonymous function from ccache.bbclass at last and  ccache is always not disabled with cmake.
So remove these useless piece of code.
Test steps:
1 create 2 build projects build-A and build-B, and update local.conf
INHERIT += "ccache"
CCACHE_DIR = "${TMPDIR}/ccache/${MULTIMACH_TARGET_SYS}/${PN}"
CCACHE_TOP_DIR = "/buildarea5/kkang/WRL10.CD/build-clang-May14/tmp-glibc/ccache" …
> Fix error when ccache enabled

- conf/nonclangable.conf
- recipes-devtools/clang/clang/0028-Add-libgcc-to-link-step-for-libcxx.patch
- recipes-devtools/clang/clang_git.bb
- recipes-devtools/clang/common.inc
- recipes-devtools/clang/compiler-rt_git.bb
- recipes-devtools/clang/openmp_git.bb
When working on #327, I have noticed that even on poky/OE zeus branches, when using meta-clang master, everything was fine for libcxx on armv5e, and that the fix was actually not far from the current zeus HEAD.
This fixes #327 by merging the few commits between the fix from master to zeus.
> Fix libcxx build for armv5e on zeus

- conf/nonclangable.conf
- recipes-devtools/clang/clang.inc
apt 1.8.2+ does not compile with clang, clang is finding narrowing
warnings and printf function is redefined in tests which confuses the
function signatures from libc when fortify is enabled, its therefore
disabled for now
--- …
> apt: Disable c++11-narrowing and fortify

- dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc/0001-tools-opensnoop-snoop-do_sys_openat2-for-kernel-v5.6.patch
- dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc_0.13.0.bb
Since kernel v5.6, fddb5d430ad9 ("open: introduce openat2(2) syscall"),
do_sys_openat2 instead of do_sys_open has been used as entry function for open.
Signed-off-by: He Zhe <zhe.he@windriver.com>
---
> bcc: Make opensnoop compatible with kernel v5.6 and later

- dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc/0001-Add-KBUILD_MODNAME-flag-to-default-cflags.patch
- dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc/0001-Delete-existing-kbuild_modname-definitions.patch
- dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc_0.13.0.bb
Backport two patches to fix the following runtime failures.
Networking tools fail with include/net/flow_offload.h:304:4: error: use of
undeclared identifier 'KBUILD_MODNAME'.
Signed-off-by: He Zhe <zhe.he@windriver.com>
--- …
> bcc: Fix KBUILD_MODNAME errors for kernel 5.7 and latter

- classes/clang.bbclass
- recipes-devtools/clang/clang/0025-clang-driver-Add-dyld-prefix-when-checking-sysroot-f.patch
- recipes-devtools/clang/common.inc
Supersedes #339 "Usrmerge support for Clang"
===================================================
These changes add usrmerge support for the Clang meta layer.
* there is a fix for "clang: Search for dynamic linker." commit;
* the usrmerge support is based on --dyld-prefix usage of the llvm-project-source;
> Usrmerge support for Clang

- .drone.yml
Currently it expect the common branch names like master and dunfell
match between meta-clang and yoe which may not be case
---
> Update drone triggers for dunfell

- recipes-devtools/clang/clang.inc
pigz, which stands for parallel implementation of gzip, is a
fully functional replacement for gzip that exploits multiple
processors and multiple cores to the hilt when compressing data.
do_package uses pigz to compress data to speed up the time
if there is pigz available on the build server.
But for some big package such as clang, there comes below
error during do_package.
gzip: stdout: Cannot allocate memory
tar: TOPDIR/sstate-cache/20/80/sstate:clang:cortexa57-wrs-linux:10.0.1:r0:cortexa57:3:20808f8a746b00ec9470a81057c8595d878cfe8c565cfbcbbaa3ea870528ee34_package.tgz.QF5dss8M: Wrote only 8192 of 10240 bytes
tar: Child returned status 1
tar: Error is not recoverable: exiting now
So set the default pigz thread for clang and the user also can
customize the pigz thread such as …
> clang: set the default pigz thread

- dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc/0001-CMakeLists.txt-override-the-PY_CMD_ESCAPED.patch
- dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc_0.15.0.bb
Override the PY_CMD_ESCAPED as the PY_CMD_ESCAPED is constructed by
the full path of the python3. In some cases, the path is so long and
result in the PY_CMD_ESCAPED exceeds 255 characters and comes below
do_configure error:
| CMake Error at src/python/CMakeLists.txt:18 (configure_file):
|   configure_file Problem configuring file
|
| CMake Error: Could not open file for write in copy operation /buildarea1/test/wr_build/wr1020_20200909_bcc/bcc_long_Kernel/auto-standalone_next/200827/lxbuilds/Intel-Snow-Ridge-NS_platform_up/intel-x86-64-standard-glibc-std/wrlinux/build/tmp-glibc/work/corei7-64-wrs-linux/bcc/0.15.0-r0/build/src/python/bcc--buildarea1-test-wr_build-wr1020_20200909_bcc-bcc_long_Kernel-auto-standalone_next-200827-lxbuilds-Intel-Snow-Ridge-NS_platform_up-intel-x86-64-standard-gl …
> bcc: override the PY_CMD_ESCAPED

- conf/nonclangable.conf
It uses GNU asm which clang's internal assembler gets confused with
and can not interpret .eh_frame section permissions and type
---
> libffi: Do not use internal assembler on mips64

- recipes-devtools/clang/clang_git.bb
Command 'bitbake <myimage> -c populate_sdk' fails with
clang-9: error: invalid linker name in argument '-fuse-ld=gold'.
Using the lld linker fixes the problem.
Signed-off-by: Winfried Dobbe <winfried.dobbe@xmsnet.nl>
---
> clang: fix build failure, unrecogn. link option '-fuse-ld=gold' (#368)

- .github/workflows/yoe.yml
This is already taken care in oe-core now
---
> github/workflows: Do not sed weston.ini for fbdev-backend.so

- recipes-devtools/clang/clang_git.bb
This helps in running ptests e.g. perl which encodes the compiler during
cross-compile and it is <cross-compile>-clang and not simply `clang`
since these tests are configured and compiled on build host and run on
target, its requied to have same names on target as well.
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you …
> clang: Create symlinks with cross compile tuples

- classes/clang.bbclass
The -mmusl flag is GCC specific, Clang supports MUSL differently.
Prevents clang-11: error: unknown argument: '-mmusl'
Verified it does not affect the GCC toolchain.cmake build.
Signed-off-by: Leon Woestenberg <leon@sidebranch.com>
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but …
> classes/clang.bbclass: Remove -mmusl flag from toolchain.cmake.

- recipes-devtools/clang/clang_git.bb
Just build BPF and AMDGPU (needed by mesa) when building target clang
along with the target arch
Pass  -DNDEBUG -g0 to CXXFLAGS to strip debug info, current amount of
debug info is is humungous ( even with -g1 ) some binaries are > 1G
in size, it takes a long time to link them and also package them since
we have a strip debug info step which takes forever
This should speedup clang build significantly
---
- '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in future, security/performance issues, …
> clang: Do not build all native targets for target as well

- recipes-devtools/castxml/castxml_git.bb
CastXML is an AST analysis tool similar to and succeeding gccxml. It
is used to generate an XML description of a C or C++ abstract syntax
tree.
Signed-off-by: Daniel McGregor <daniel.mcgregor@vecima.com>
--- …
> CastXML: new recipe

- recipes-devtools/clang/clang_git.bb
- recipes-devtools/clang/openmp_git.bb
> Enable building clang for riscv32/64 target

- recipes-devtools/clang/clang/0026-OpenCL-Fix-support-for-cl_khr_mipmap_image_writes.patch
- recipes-devtools/clang/common.inc
This patch is already merged in llvm-11.
Signed-off-by: Naveen Saini <naveen.kumar.saini@intel.com>
---
> clang: Enable C functions for cl_khr_mipmap_image_write extension

- recipes-core/meta/clang-environment.inc
clang-tidy doesn't process compilation flags like "-mlittle-endian" and "sysroot". The current export tries to use those flags, which makes clang-tidy fail like in the following example:
> $ aarch64-poky-linux-clang-tidy fibonacci.cpp -mlittle-endian --sysroot=/opt/mgu22/sysroots/aarch64-poky-linux
> LLVM ERROR: CommonOptionsParser: failed to parse command-line arguments. [CommonOptionsParser]: aarch64-poky-linux-clang-tidy: Unknown command line argument '-mlittle-endian'.  Try: 'aarch64-poky-linux-clan$
> aarch64-poky-linux-clang-tidy: Did you mean '--list-checks'?
> aarch64-poky-linux-clang-tidy: Unknown command line argument '--sysroot=/opt/mgu22/sysroots/aarch64-poky-linux'.  Try: 'aarch64-poky-linux-clang-tidy --help'
> aarch64-poky-linux-clang-tidy: Did you mean …
> Remove compiler arguments from CLANG_TIDY_EXE 

- recipes-devtools/clang/clang_git.bb
The nativesdk gcc is build shared, nativesdk clang should also build shared.
This saves more than 500MB of disk space in sdk.
Signed-off-by: Daniel Dittmann <daniel.dittmann@rohde-schwarz.com>
> build shared nativesdk clang

- recipes-core/meta/meta-environment.bbappend
clang-tidy does not know compiler arguments
Signed-off-by: Daniel Dittmann <daniel.dittmann@rohde-schwarz.com>
> do not use compiler arguments for clang-tidy (backport to dunfell)

- recipes-devtools/clang/openmp_git.bb
> openmp: Disable for riscv32

- recipes-devtools/clang/clang/0027-InstCombine-visitBitCast-do-not-crash-on-weird-bitca.patch
- recipes-devtools/clang/common.inc
This patch is already merged in llvm-11.
Ref:
https://github.com/llvm/llvm-project/commit/381054a989ebd0b585fee46f2a01a7c5de10acf7
Signed-off-by: Naveen Saini <naveen.kumar.saini@intel.com>
---
> llvm: Do not crash on weird `bitcast <1 x i8*> to i8*`

- classes/clang.bbclass
- classes/lto.bbclass
- conf/layer.conf
- conf/nonclangable.conf
- recipes-core/musl/musl_%.bbappend
- recipes-devtools/clang/clang_git.bb
> Fix QT on rv32 and use -mo-relax to compile so lld can be used for LTO

- classes/clang.bbclass
The tune file for octeontx2 has been added into oe-core by commit
ad4f82742c6f ("tune-octeontx2.inc: Add tune for Marvell OCTEON TX2
core"). But the clang doesn't support this core yet. So remove the
-mcpu from the TUNE_CCARGS to fix the build failure for the octeontx2
core.
Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, …
> clang.bbclass: Remove -mcpu option for the octeontx2 core

- conf/nonclangable.conf
New version of ppp uses gcc specific options and nested functions which
clang does not support
---
> ppp: Mark non-clangable

- recipes-core/meta/clang-environment.inc
This commit fixes an issue (#418) when building a cmake based project where clang-tidy is configured as co-compiler. Without this option clang-tidy will fail as it cannot determinate the target architecture.
--- …
> Add the target option to the CLANG environment variables

- recipes-devtools/clang/clang/0027-For-x86_64-set-Yocto-based-GCC-install-search-path.patch
- recipes-devtools/clang/common.inc
Under Yocto host, while using clang-native to build, it searches
install host gcc failed which causing include file not found
[snip]
|clang++ -target x86_64-linux  -MMD -MF src/base/files/file_path_constants.o.d -I../../../tools/gn/src -I. \
-isystem/tmp-glibc/work/x86_64-linux/gn-native/87.0.4280.141-r0/recipe-sysroot-native/usr/include -O2 -pipe \
-std=c++17 -c ../../../tools/gn/src/base/files/file_path_constants.cc -o src/base/files/file_path_constants.o
|../../../tools/gn/src/base/files/file_path_constants.cc:7:10: fatal error: 'iterator' file not found
|#include <iterator>
|         ^~~~~~~~
[snip]
Set three Yocto based GCC triple: poky, oe-core and wind river
Before aplly the patch
[snip]
$ ../recipe-sysroot-native/usr/bin/clang++ -v
clang version 11.0.1 …
> clang: for x86_64, set Yocto GCC install search path

- classes/clang.bbclass
oe-core's ccache.bbclass contains:
export CCACHE_COMPILERCHECK ?= "%compiler% -dumpspecs"
which sets a default value and allows others to easily override the
value of CCACHE_COMPILERCHECK if they wish to. Let's update
clang.bbclass to also set only the default value of CCACHE_COMPILERCHECK
too.
Signed-off-by: Mike Crowe <mac@mcrowe.com>
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major …
> clang.bbclass: Set CCACHE_COMPILERCHECK as default value

- recipes-devtools/clang/compiler-rt_git.bb
Sanitizers need libcrypt to build, so when using llvm runtime this
becomes important to break the cyclic dependency
compiler-rt->libxcrypt->compiler-rt
Fixes Issue #425
--- …
> compiler-rt: Disable sanitizer builds

- conf/layer.conf
Because bcc and bpftrace have been set in NON_MULTILIB_RECIPES, 'bcc'
rprovides 'lib32-bcc'. So when multilib is enabled, it is 'bcc' rather
than 'lib32-bcc' installed to lib32 image such as lib32-core-image-minimal.
Then the runtime dependency 64-bit package python3-core is installed
accordingly. It causes 32-bit python modules which contains .so library
do not work any more. For example, it fails to run command 'dnf':
| ImportError: /usr/lib/python3.9/site-packages/libdnf/_error.so: wrong ELF class: ELFCLASS32
Remove bcc and bpftrace from NON_MULTILIB_RECIPES to make sure they are
not installed to lib32 images and mess images up.
Signed-off-by: Kai Kang <kai.kang@windriver.com>
---
- '*Approve*' if this change would be acceptable in the codebase …
> layer.conf: remove bcc and bpftrace from NON_MULTILIB_RECIPES

- recipes-devtools/clang/libclc_git.bb
Don't override cmake specific compiler options
Add BBCLASSEXTEND = "native nativesdk"
Depend on spirv-tools if LLVM version is 12 or newer
Signed-off-by: Zoltán Böszörményi <zboszor@pr.hu>
---
> libclc fixes

- recipes-devtools/spirv-llvm-translator/spirv-llvm-translator/0001-cmake-allow-to-enable-disable-ccache.patch
- recipes-devtools/spirv-llvm-translator/spirv-llvm-translator_git.bb
Native build is failing, error log:
~/build/tmp/work/x86_64-linux/spirv-llvm-translator-native/12.0.0-r0/git/lib/SPIRV/SPIRVLowerSPIRBlocks.cpp
| /bin/sh: 1: ccache: not found
Signed-off-by: Naveen Saini <naveen.kumar.saini@intel.com>
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but …
> spirv-llvm-translator: disable ccache

- recipes-devtools/clang/clang_git.bb
LLDTargets.cmake (generated and installed by the lld build)
references lld this way:
add_executable(lld IMPORTED)
set_property(TARGET lld PROPERTY ENABLE_EXPORTS 1)
This way lld can be used by plugins to get their symbols from,
pretty much like PHP modules that resolve their symbols from the
php executable during runtime linking.
At least https://github.com/RadeonOpenCompute/ROCm-CompilerSupport
uses lld's cmake files as opposed to using only llvm and previously
failed with:
|   The imported target "lld" references the file
|
|      ".../tmp-sicom-glibc/work/corei7-64-sicom-linux/amd-comgr/4.0.0-r0/recipe-sysroot/usr/bin/lld"
|
|   but this file does not exist.  Possible reasons include:
|
|   * The file was deleted, renamed, or moved to another location.
|
|   * An install or uninstall …
> clang: Install lld for target builds

- dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc/0001-cmake-link-dynamically-to-libclang-cpp-if-found-and-.patch
- dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc/0002-cmake-always-link-to-packaged-libbpf-if-CMAKE_USE_LI.patch
- dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc/0003-Remove-libbcc-no-libbpf-shared-library-change-libbcc.patch
- dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc/0004-cmake-look-for-either-static-or-dynamic-libraries.patch
- dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc_0.17.0.bb
Link bcc dynamically against libbpf. This reduces the size of libbcc.so
from 68 MB to 3 MB.
Backport some patches from upstream which are needed for the actual
dynamic linking.
Depends on openembedded/meta-openembedded#320
Signed-off-by: Matteo Croce <mcroce@microsoft.com>
--- …
> bcc: link with dynamic libbpf

- recipes-devtools/clang/clang/0029-llvm-Recognize-yoe-and-poky-as-OE-distro.patch
it will now find the correct libraries for wrlinux
Signed-off-by: Yi Fan Yu <yifan.yu@windriver.com>
* we can carry it as a wrlinux patch, but ideally it gets merged here.
---
- [x ] Changes have been tested
- [x ] `Signed-off-by` is present
- [x ] The PR complies with the [Open Embedded Commit Patch Message Guidelines](http://www.openembedded.org/wiki/Commit_Patch_Message_Guidelines)
- '*Comment*' if you don't feel you have enough information …
> clang: Add wrs to OE-distro

- .github/workflows/yoe.yml
This is needed for weston to launch since 'runqemu nograhic' no longer
specify right -vga option in OE-core after commit 9f8d049dbbe0b1760979d9f3b745124abfc54c90
---
> github/workflows: Set DISPLAY variable in environment

- recipes-devtools/clang/clang/0026-For-x86_64-set-Yocto-based-GCC-install-search-path.patch
- recipes-devtools/clang/llvm-project-source.inc
This is to avoid a ton of shell variables becoming dependencies
Add every case in a new line
---
> llvm-project-source: Re-implement add_more_target_vendors in python

- dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace/0001-bpforc.h-Include-optional-header.patch
- dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace_0.11.4.bb
This is needed for fixing builds with master since clang 12 has dropped
ORCv1 APIs
Add a patch to fix build with clang-12
---
> bpftrace: Update to using master branch

- recipes-devtools/clang/llvm-project-source.inc
Generate all possible vendor name that a multilib build could use
by using the variable MULTILIB_VARIANTS.
ex: {TARGET_VENDOR} {TARGET_VENDOR}mllib32
Fixes build issue when compiling lib32-compiler-rt
where clang has issue detecting gcc toolchain.
when clang --print-search-dirs:
lib32-recipe-sysroot//usr/lib/i686-wrsmllib32-linux
should be
lib32-recipe-sysroot//usr/lib/i686-wrsmllib32-linux/10.2.0/
Signed-off-by: Yi Fan Yu <yifan.yu@windriver.com>
---
- [ X] Changes have been tested
- [ X] `Signed-off-by` is present
- [ X] The PR complies with the [Open Embedded Commit Patch Message Guidelines](http://www.openembedded.org/wiki/Commit_Patch_Message_Guidelines)
- '*Approve*' if this change would be acceptable in the codebase (even if there are minor …
> llvm-project-source: Add multilib vendor support

- conf/layer.conf
> layer.conf: Drop gatesgarth

- recipes-devtools/clang/llvm-project-source.inc
This helps in ensuring that SDK elements are built correctly as well,
at present we get right builds for cross/target/native clang but not for
nativesdk since it use SDK_VENDOR string for vendor eg. -yoesdk which
currently is not added to known OE vendors, as a result nativesdk-clang
does not build since crosssdk clang can not find runtime files e.g.
libgcc
Cc: Martin Jansa <Martin.Jansa@gmail.com>
---
- '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in future, security/performance issues, …
> clang: Add SDK_VENDOR string to CLANG_EXTRA_OE_VENDORS

- recipes-devtools/spirv-llvm-translator/spirv-llvm-translator_git.bb
The trailing slash caused the mirror name endswith a dot which looks strange:
github.com.KhronosGroup.SPIRV-LLVM-Translator.
The slash is not needed, so remove it.
Signed-off-by: Robert Yang <liezhi.yang@windriver.com>
Signed-off-by: Changqing Li <changqing.li@windriver.com>
--- …
> spirv-llvm-translator: Remove a trailing slash from SRC_URI

- recipes-devtools/clang/clang/0036-Drop-the-git-suffix-from-various-version-variables.patch
- recipes-devtools/clang/common.inc
other recipe like intel-graphics-compiler, config failed with
below error:
[IGC] Could not find the LLVM dylib.  Aborting.
with a suffix in library name make other recipe cannot found it.
Backport a patch from 12.0.0 to fix this.
Signed-off-by: Changqing Li <changqing.li@windriver.com>
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of …
> clang: drop git suffix from version variables

- recipes-devtools/clang/clang_git.bb
After enable multilib, libdir is /usr/lib64, but in llvm's
CMakelist.txt, the install path is hardcode as /usr/lib
eg:
${CMAKE_BINARY_DIR}/lib/libscanbuild/resources/${resource}
Signed-off-by: Changqing Li <changqing.li@windriver.com>
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but …
> clang: fix do_package error when multilib enabled

- conf/layer.conf
- dynamic-layers/selinux/android-tools/android-tools-conf-configfs/10-adbd-configfs.conf
- dynamic-layers/selinux/android-tools/android-tools-conf-configfs/android-gadget-cleanup
- dynamic-layers/selinux/android-tools/android-tools-conf-configfs/android-gadget-setup
- dynamic-layers/selinux/android-tools/android-tools-conf-configfs/android-gadget-start
- dynamic-layers/selinux/android-tools/android-tools-conf-configfs_1.0.bb
- dynamic-layers/selinux/android-tools/android-tools-conf/android-gadget-setup
- dynamic-layers/selinux/android-tools/android-tools-conf_1.0.bb
- dynamic-layers/selinux/android-tools/android-tools/adb_mk_change_out_dir.patch
- dynamic-layers/selinux/android-tools/android-tools/android-tools-adbd.service
- dynamic-layers/selinux/android-tools/android-tools/fastboot_compile_remove_gtest.patch
- dynamic-layers/selinux/android-tools/android-tools/fastboot_dont_use_sparse_file_import_auto_in_load_buf_fd.patch
- dynamic-layers/selinux/android-tools/android-tools/fastboot_mk_change_out_dir.patch
- dynamic-layers/selinux/android-tools/android-tools/img2simg_change_out_dir.patch
- dynamic-layers/selinux/android-tools/android-tools/libadb_mk_change_out_dir.patch
- dynamic-layers/selinux/android-tools/android-tools/libbacktrace_mk_change_out_dir.patch
- dynamic-layers/selinux/android-tools/android-tools/libbase_mk_change_out_dir.patch
- dynamic-layers/selinux/android-tools/android-tools/libcrypto_mk_change_out_dir.patch
- dynamic-layers/selinux/android-tools/android-tools/libcrypto_utils_mk_change_out_dir.patch
- dynamic-layers/selinux/android-tools/android-tools/libcutils_mk_change_out_dir.patch
- dynamic-layers/selinux/android-tools/android-tools/libext4_utils_mk_change_out_dir.patch
- dynamic-layers/selinux/android-tools/android-tools/libfec_mk_change_out_dir.patch
- dynamic-layers/selinux/android-tools/android-tools/liblog_mk_change_out_dir.patch
- dynamic-layers/selinux/android-tools/android-tools/libsparse_mk_change_out_dir.patch
- dynamic-layers/selinux/android-tools/android-tools/libunwind_mk_change_out_dir.patch
- dynamic-layers/selinux/android-tools/android-tools/libziparchive_mk_change_out_dir.patch
- dynamic-layers/selinux/android-tools/android-tools/rules_yocto.mk
- dynamic-layers/selinux/android-tools/android-tools/simg2img_change_out_dir.patch
- dynamic-layers/selinux/android-tools/android-tools/use_name_space_std_to_compile_libbacktrace.patch
- dynamic-layers/selinux/android-tools/android-tools_10.0.0.r36.bb
An older version is present in the meta-oe layer.
Took the old recipe and adapted it in the following way:
--Deleted all the old patches that were applicable for
old version.
--Used all the makefiles that come with the new version
directly from the source code, just modifying them
to install output to a specific folder as below
a)added rules_yocto.mk that will mimic the debian/rules
b)modified the makefiles of the components to output to
a common dir.
c)
Built boringssl crypto with the option -DOPENSSL_NO_ASM
to solve the below errors
libcrypto.so.0: undefined reference to `aes_hw_encrypt'
libcrypto.so.0: undefined reference to `aes_hw_set_encrypt_key'
libcrypto.so.0: undefined reference to `gcm_gmult_v8'
libcrypto.so.0: undefined reference to `gcm_init_v8'
libcrypto.so.0: undefined …
> upgrade of android-tools to 10.0.0.r36

- recipes-devtools/spirv-llvm-translator/spirv-llvm-translator_git.bb
Fetching SPIRV-Headers, which provides required spirv.hpp headers
https://github.com/KhronosGroup/SPIRV-Headers.git
Signed-off-by: Naveen Saini <naveen.kumar.saini@intel.com>
---
> spirv-llvm-translator: switch to release llvm_release_130 branch

- recipes-devtools/spirv-llvm-translator/spirv-llvm-translator_git.bb
Since it uses multiple fetch URIs make it explicit to define SRCREV_FORMAT
---
> spirv-llvm-translator: Define explicit SRCREV_FORMAT

- recipes-devtools/clang/llvm-project-source.inc
Using regular multilib variants prevents sharing state between machines
with dissimilar multilibs, or non-multilib machines. Since there's no
harm in having extra multilib triples, use the full set for all builds.
Signed-off-by: Dan McGregor <dan.mcgregor@usask.ca>
--- …
> clang: use global multilib variants

- recipes-devtools/clang/clang.inc
Changes in this set
* d7b669b3a303 [clang] don't mark as Elidable CXXConstruct expressions used in NRVO
* ee6913cc8317 [analyzer] Add 13.0.0 release notes
* d0f0b5b99262 Thread safety analysis: Warn when demoting locks on back edges
* 80f974e40f81 [AArch64][GlobalISel] Use ZExtValue for zext(xor) when invert tb(n)z
* 5b95eb0b442e [debuginfo-test][cross-project-tests] Release note for new project name
* b96ee8f581f6 [X86] combineX86ShuffleChain - ensure we only peek through bitcasts to vectors (PR51858)
* dda88bfc06b5 [clang][scan-build] Use cc/c++ instead of gcc/g++ on OpenBSD.
* 08642a395f23 Fix syntax error in Clang release notes
* 6a5ccb2ec438 [compiler-rt] Implement __clear_cache() on OpenBSD/riscv64
* 6aa054242d60 [LLD] Add required `ppc` target to the test cases. NFC
* 8d78ac26f475 …
> clang: Update to 13.0.0-rc4

- classes/clang.bbclass
- recipes-devtools/clang/clang_git.bb
We can not use nativesdk variants of libcxx and compiler-rt yet when
compiling nativesdk-clang because, it will need this compiler to build
them, so solve this catch-22, since we do not use the runtime built
during compiler builds, use libgcc/libstdc++ to pass cmake tests
during configure, this should be fine as it will be not needed for final
builds where nativesdk-clang will be used, it can still default to llvm
runtime on SDK host
---
- '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in …
> nativesdk-clang: Fix build when using RUNTIME = llvm

- recipes-devtools/clang/clang/0028-nfc-Fix-missing-include.patch
- recipes-devtools/clang/common.inc
This affects LLVM < 12, so backport directly to dunfell. This adds a missing
include that was breaking the build with recent libstdc++ releases on the
host system (versions 11 and above).
> clang: Backport missing include fix from upstream.

- dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc_0.20.0.bb
github has stopped supporting anonymous git protocol and bitbake now
warns about branch not being explicit, master is no more a viable
fallback
---
> bcc: Specify branch and protocol in git SRC_URI

- recipes-devtools/clang/clang_git.bb
lnr is deprecated, simply use ln -rs instead.
Signed-off-by: Ross Burton <ross.burton@arm.com>
---
> clang: don't use lnr

- conf/nonclangable.conf
glibc is not yet compilable for clang
---
> glibc-tests: Pin to use gcc

- recipes-devtools/clang/clang.inc
Changes in this bump
* 19b8368225dc [X86][VARARG] Assign MMO earlier to   avoid prolog insert point been sunk across VASTART_SAVE_XMM_REGS
* 41c85bbb43e4 [X86][NFC] Pre-commit test to show prolog insert problem
* 9dc7d6d5e326 [SystemZ] Give the EXRL_Pseudo a size value of 6 bytes.
* 32bb956916e3 Bad SLPVectorization shufflevector replacement, resulting in write to wrong memory location
* 93edfb23b18b [SLP][NFC]Add a test to show an issue with incorrectly extracted pointers.
* 162f3f18c945 [Aarch64] Correct register class for pseudo instructions
* 8be24d19fefa [MergeICmps] Don't merge icmps derived from pointers with addressspaces
* 9e084f4194e6 Fix building with GCC 12:
* d5159b99105d MLIR can't support -Bsymbolic link option, fail at CMake time with a helpful message instead of broken ru …
> clang: Update to 13.0.1-rc1

- classes/clang.bbclass
- conf/nonclangable.conf
libcxx does not build for armv5 due to atomic locks issue
and compile-rt cross build needs to be fixed for ppc32
---
> Use GCC runtime on ppc32 and armv5

- dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc_0.20.0.bb
While building bcc for the target it depends on flex target recipe. So
add that dependency explicity.
Signed-off-by: Sumit Garg <sumit.garg@linaro.org>
> bcc: Add explicit dependency on flex target recipe

- dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc_0.20.0.bb
While building bcc for the target it depends on flex target recipe. So
add that dependency explicity.
Signed-off-by: Sumit Garg <sumit.garg@linaro.org>
> [honister] bcc: Add explicit dependency on flex target recipe

- recipes-devtools/clang/clang/0037-Fix-lib-paths-for-OpenEmbedded-Host.patch
- recipes-devtools/clang/clang/0038-Correct-library-search-path-for-OpenEmbedded-Host.patch
- recipes-devtools/clang/common.inc
- recipes-devtools/clang/llvm-project-source.inc
Build on OpenEmbedded Host, compiler-rt-native do_configure failed with
following error:
compiler-rt-native/13.0.1-r0/recipe-sysroot-native/usr/bin/clang -target x86_64-linux
-isystem/path/to/x86_64-linux/compiler-rt-native/13.0.1-r0/recipe-sysroot-native/usr/include
-O2 -pipe
/path/to/compiler-rt-native/13.0.1-r0/recipe-sysroot-native/usr/share/cmake-3.21/Modules/CMakeCCompilerABI.c`
|     /build/tmp-glibc/hosttools/ld: cannot find crtbeginS.o: No such file or directory
|     /build/tmp-glibc/hosttools/ld: cannot find -lgcc
|     /build/tmp-glibc/hosttools/ld: cannot find -lgcc
|     clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
Since OpenEmbedded Host's gcc install path is different with clang's
default search form, patch for OpenEmbedded Host's gcc …
> clang: for x86_64, correct GCC install search path for OpenEmbedded Host

- recipes-devtools/clang/clang.inc
- recipes-devtools/clang/clang_git.bb
Fixes brought in
* f3394dc82c20 [libc++] Fix wrongly non-inline basic_string::shrink_to_fit
* 52bfd2c1ccd8 [ELF] Do not report undefined weak references in shared libraries
--- …
> clang: Update to latest on 13.x

- recipes-devtools/clang/clang-cross_git.bb
```virtual/${TARGET_PREFIX}binutils``` shall be used and not ```binutils-cross-${TARGET_ARCH}```
In the case of an external arm toolchain, ```binutils-cross-aarch64``` does not exist and creates following error:
```
Missing or unbuildable dependency chain was: ['tisdk-base-image', 'packagegroup-core-standalone-sdk-target', 'libcxx-dev', 'compiler-rt', 'clang-cross-aarch64', 'binutils-cross-aarch64']
```
Signed-off-by: Guillaume Pais <guillaume.pais@siemens.com>
---
- '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in future, …
> DEPENDS on virtual/${TARGET_PREFIX}binutils

- classes/clang.bbclass
- conf/layer.conf
Or I should set up a new RUNTIME condition? Because in Android, only the C++ environment comes from LLVM but the libc is not .
Signed-off-by: Hsia-Jun(Randy) Li <randy.li@synaptics.com>
---
> clang: support android runtime

- recipes-devtools/clang/clang_git.bb
This helps in creating cross utilities to be used during OE cross builds
as noted in
Issue #491
---
> clang: Create cross symlinks for more binutils

- recipes-devtools/clang/clang/0039-run-clang-tidy-on-unique-files-only.patch
run-clang-tidy.py is being run on unique files only
when using this patch
Signed-off-by: Serikzhan Kazi <doze-tile-ruse-exit@mbition.io>
---
> clang-tools-extra: apply upstream patch

- conf/nonclangable.conf
The code has inline arm asm in header files which is not compilable with
clang's internal assembler.
---
> concurrencykit: Disable internal clang assembler

- recipes-devtools/clang/clang/0029-OpenMP-link-fix.patch 
- recipes-devtools/clang/openmp_git.bb
-fixes "version node not found for symbol omp_get_num_places_@@VERSION"
Signed-off-by: Joel Winarske <joel.winarske@gmail.com>
Build matrix is currently running.  Will move from WIP state after builds all pass.
---
- [x ] `Signed-off-by` is present
- [ x] The PR complies with the [Open Embedded Commit Patch Message Guidelines](http://www.openembedded.org/wiki/Commit_Patch_Message_Guidelines)
- '*Comment*' if you don't feel you have enough …
> [WIP] OpenMP Link fix

- classes/clang.bbclass
Commit a494bbb6ec44 ("clang: support android runtime") introduced an
unrelated change causing builds with RUNTIME="llvm" and COMPILER_RT not
set to get a dependency on virtual/${TARGET_PREFIX}compilerlibs.
This is clearly unrelated to addition of support for android runtime,
and causing unwanted depdencies to gcc-runtime for LLVM builds.
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have …
> clang: Remove unintended dependency on gcc-runtime

- classes/clang.bbclass
Signed-off-by: yangpeng1995 <1336781165@qq.com>
---
> clang.bbclass: Fix typo about big.LITTLE tune options

- classes/clang.bbclass
These tools are better integrated with clang produced output consumption
pipeline, therefore use them when using clang as compiler
---
> clang.bbclass: Use llvm provided binutils when using toolchain-clang

- dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace_0.14.1.bb
Enable riscv64 as the support is now available
this update is needed for it to work with clang14
---
> bpftrace: Upgrade to latest master

- classes/clang.bbclass
do_populate_sysroot will execute the cross STRIP as part of the
processing. In non-clang builds this is present via POPULATESYSROOTDEPS
pulling in binutils, but in clang builds STRIP is set to llvm-strip which
obviously isn't part of binutils.
Set POPULATESYSROOTDEPS correctly to ensure that do_populate_sysroot has
the strip binary available.
Signed-off-by: Ross Burton <ross.burton@arm.com>
> clang: set POPULATESYSROOTDEPS so that strip is present

- conf/nonclangable.conf
This is to workaround issue [1] seen with LLVM mips
[1] https://github.com/llvm/llvm-project/issues/54213
---
> libbsd: Use GNU objdump on mips

- conf/nonclangable.conf
llvm versions have a known bug
---
> gosu: Use binutils strip and objcopy

- dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc_0.24.0.bb
Disable LuaJIT on rv64 since its not yes ported
---
> bcc: Enable riscv64 builds

- conf/nonclangable.conf
it will take some effort to fix it going with clang 14
due to VSX/altivec intrinsics conflicts
---
> opencv: Use gcc for ppc64

- classes/clang.bbclass
When RUNTIME=="llvm" the libcxx entry will be added in a separate if clause
right after this.  We don't need it twice.
Signed-off-by: Esben Haabendal <esben.haabendal@huawei.com>
---
> clang: Avoid double libcxx in BASE_DEFAULT_DEPS

- recipes-devtools/clang/openmp_git.bb
ppc is not yet supported by openmp
see https://github.com/llvm/llvm-project/blob/main/openmp/runtime/cmake/LibompGetArchitecture.cmake#L16
---
> openmp: Exclude powerpc

- recipes-devtools/clang/clang/D122505.diff
- recipes-devtools/clang/common.inc
Workaround a llvm-objdump issue reported in
https://github.com/llvm/llvm-project/issues/54456
---
> dhcp-relay,apache2:Fix llvm objdump

- classes/clang.bbclass
- recipes-devtools/rpm/rpm_%.bbappend
openmp is not ported for ppc32
---
> rpm: Do not use openmp on ppc

- dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace/0001-Detect-new-BTF-api-btf_dump__new-btf_dump__new_v0_6_.patch
- dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace_0.14.1.bb
Fixes
git/src/btf.cpp:651:10: error: no matching function for call to 'btf_dump__new'
---
> bpftrace: Fix build with new libbpf

- conf/layer.conf
- recipes-devtools/clang/clang.inc
Brings these changes
* 1f9140064dfb Bump version to 14.0.3
* 2e7e14177186 workflows: Add a test to ensure that the LLVM version is correct
* 0e27d08cdeb3 [RISCV] Fix crash for section alignment with .option norvc
* a36801750327 [asan] Always skip first object from dl_iterate_phdr
* 1f4c7b2a9120 [RISCV] Don't emit fractional VIDs with negative steps
* e19be4195b87 [RISCV] Add another test showing incorrect BUILD_VECTOR lowering
* 9efcce92b55b [RISCV] Fix lowering of BUILD_VECTORs as VID sequences
* 21ce6cfd1d93 [RISCV] Add tests showing incorrect BUILD_VECTOR lowering
* 58d5fbe2c20b [llvm-mt] Add support /notify_update
* 50c6ba751fa2 [RISCV] Only try LUI+SH*ADD+ADDI for int materialization if LUI+ADDI+SH*ADD failed.
* dc30b0d3320d [ELF] --emit-relocs: fix missing STT_SECTION when the first …
> clang: Upgrade to 14.0.3

- conf/layer.conf
- recipes-devtools/clang/clang.inc
This brings
* b950bd2ce7ff Bump version to 14.0.5
* 29f1039a7285 [CUDA][HIP] Externalize kernels with internal linkage
* e6de9ed37308 [CUDA][HIP] Externalize kernels in anonymous name space
* fecfc8394484 AST: Move __va_list tag back to std conditionally on AArch64.
* 725d57c39039 AST: Make getEffectiveDeclContext() a member function of ItaniumMangleContextImpl. NFCI.
* 0009cdbd8a3a [clang][NFC] Remove IgnoreLinkageSpecDecls
* 53eaee6bf3b3 [clang][NFC] Standard substitution checking cleanup
* c81f3d00cbd4 [AVR] Generate 'rcall' instead of 'call' on avr2 and avr25
* 5f6fe6b93e85 [AVR] Fix incorrect calling convention for varargs functions
* 42fe7ccbeb44 [SystemZ] Bugfix for symbolic displacements.
* f45a01e4a170 [libc++][CI] added XFAIL LIBCXX-AIX-FIXME to new runnning test cases after …
> clang: Update to 14.0.4+

- dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc/0001-Vendor-just-enough-extra-headers-to-allow-libbpf-to-.patch
- dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc_0.24.0.bb
Currently bcc builds against a vendored copy of libbpf. This causes problems for bpftrace which is built against bcc and the system libbpf. The resulting version skew between the vendored and system versions of libbpf resulting in a SEGV whenever bpftrace is used.
Although `--help` and `-l` (list probe points) work OK that is because they do not actually use BPF! Anything that does use BPF will crash immediately,including `bpftrace --info` and simple one-liners such as:
~# bpftrace -e 't:raw_syscalls:sys_exit { printf("%s", comm); }'
Attaching 1 probe...
Segmentation fault
Fixes: https://github.com/iovisor/bpftrace/issues/2173
Fixes: bb3e56b06f9d ("bpftrace: Fix build with new libbpf")
Currently I have fixed this in two parts, firstly we make de-vendoring work by using a nasty hack and …
> bcc: De-vendor libbpf

- recipes-devtools/clang/compiler-rt_git.bb
The clang_rt.profile library is used to collect coverage information. It is a
static library, so does not introduce any additional footprint in target images.
Signed-off-by: Esben Haabendal <esben.haabendal@huawei.com>
--- …
> compiler-rt: Build clang_rt.profile library when possible

- recipes-devtools/spirv-llvm-translator/spirv-llvm-translator_git.bb
"master" branch in SPIRV-LLVM-Translator has been renamed to "main"
see https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/6db0f312c918bba14a731822b38a18726bb4ce09
Signed-off-by: Teoh Jay Shen <jay.shen.teoh@intel.com>
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but want …
> spirv-llvm-translator: Update for branch rename

- recipes-devtools/clang/clang/0036-compiler-rt-builtins-Move-DMB-definition-to-syn-opsh.patch
- recipes-devtools/clang/common.inc
Compiler-rt cross-compile for ARMv5 fails because D99282 made it an error if DMB
is used for any pre-ARMv6 targets. More specifically, the "#error only supported
on ARMv6+" added in D99282 will cause compilation to fail when any source file
which includes assembly.h are compiled for pre-ARMv6 targets. Since the only
place where DMB is used is syn-ops.h (which is only included by
arm/sync_fetch_and_* and these files are excluded from being built for older
targets), this patch moves the definition there to avoid the issues described
above.
Signed-off-by: Ming Liu <liu.ming50@gmail.com>
---
- '*Request Changes*' if this …
> compiler-rt: backport a patch fixing ARMv5 cross-compile

- recipes-devtools/clang/compiler-rt_git.bb
- recipes-devtools/clang/libcxx_git.bb
This is a backport from main [4d066667c3cbba3b88d2f8d6c5640f5f793d10b4, 9c8347351565ba4ea0b31e92cf55b29811372285] with the minimum required for building on dunfell-clang12 without the other changes made on main such as libunwind.
Signed-off-by: Chris Wulff <crwulff@gmail.com>
--- …
> clang: Backport libcxx-native build and dependency fixes from main.

- recipes-devtools/clang/clang_git.bb
- recipes-devtools/clang/compiler-rt-sanitizers_git.bb
- recipes-devtools/clang/compiler-rt_git.bb
Setting the ${HF} variable based on ${TUNE_CCARGS_MFLOAT} does only make sense
for target builds, as it defines arguments for target.  Without this fix,
building with hf machine configuration will cause problems, as native and
nativesdk triplets will be include "hf", something like "x86_64hf-linux", which
is wrong and not recognized by LLVM build/configuration system.
Signed-off-by: Esben Haabendal <esben.haabendal@huawei.com>
---
- …
> clang: Fix native and nativesdk builds for hf targets

- conf/layer.conf
- recipes-devtools/clang/clang.inc
Bring in following changes
* f28c006a5895 Bump version to 14.0.6
* aa586b6f5f55 [clang][AVR] Implement standard calling convention for AVR and AVRTiny
* ec42d3c069c7 [AVR] Add more devices
* c12386ae247c [MC][AArch64] Enable '+v8a' when nothing specified for MCSubtargetInfo
* 4d5dad43b2eb [analyzer] Fix null pointer deref in CastValueChecker
* 5b296385298f PR45879: Fix assert when constant evaluating union assignment.
* deb573739df9 [clang-tidy] `bugprone-use-after-move`: Fix handling of moves in lambda captures
* d0cd5a872f8d [clang-format] Fix SpacesInLineCommentPrefix deleting tokens.
* 3cd9df8443f8 [clang-format] Fix PointerAlignment: Right not working with tab indentation.
* d350783a0520 [LoopIdiom] Merge TBAA of adjacent stores when creating memset
* 198626ad43fd [MIPS] Address …
> clang: Update to 14.0.6

- conf/nonclangable.conf
This reverts commit 3882c27310b16e6fc097cca1966cea591769cc5c.
---
> Revert "python3: Use gcc for riscv/aarch64 and all musl"

- dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc_0.25.0.bb
Changes are here [1]
[1] https://github.com/iovisor/bcc/releases/tag/v0.25.0
---
> bcc: Upgrade to 0.25.0

- dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace/0001-Fix-segfault-when-btf__type_by_id-returns-NULL.patch
- dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace_0.14.1.bb
Fixes segfault when running i.e. bpftrace -l
Signed-off-by: Michal Wojcik <michal.wojcik@linaro.org>
---
> bpftrace: Fix segfault when btf__type_by_id returns NULL

- classes-recipe/clang-native.bbclass
- classes/clang.bbclass
- recipes-bsp/systemd-boot/systemd-boot_%.bbappend
- recipes-core/systemd/systemd_%.bbappend
- recipes-devtools/clang/libcxx_git.bb
- recipes-devtools/rust/rust-llvm_%.bbappend
- recipes-devtools/rust/rust_%.bbappend
This ensures that -stdlib=libc++ option works as expected
by adding both -lc++ -c++abi to linker command in sequence
> libcxx: Enable installing libc++.so as linker script

- recipes-devtools/clang/clang/0001-llvm-objdump-Change-printSymbolVersionDependency-to-.patch
- recipes-devtools/clang/common.inc
llvm-objdump crashes on dumping trace binary
---
> go: Use binutils objdump for aarch64/musl for now

- recipes-devtools/clang/compiler-rt-sanitizers_git.bb
Remove libclang_rt.orc and c_orc.h header since it is being installed by both compiler-rt and compiler-rt-sanitizer when built for arm.
While building for a custom test recipe ` test-sanitizer-1.0-r0`  inheriting clang and compiler-rt-sanitizer:
`ERROR: test-sanitizer-1.0-r0 do_prepare_recipe_sysroot: The file /usr/lib/clang/15.0.1/lib/linux/libclang_rt.orc-armhf.a is installed by both compiler-rt and compiler-rt-sanitizers, aborting `
`ERROR: test-sanitizer-1.0-r0 do_prepare_recipe_sysroot: The file /usr/lib/clang/15.0.1/include/orc/c_api.h is installed by both compiler-rt and compiler-rt-sanitizers, aborting `
--- …
> compiler-rt-sanitizers: fix multiple installations for orc lib

- recipes-devtools/clang/clang/0033-compiler-rt-Link-scudo-with-SANITIZER_CXX_ABI_LIBRAR.patch
- recipes-devtools/clang/clang/0034-CMake-Installable-find-modules-for-terminfo-and-libf.patch
- recipes-devtools/clang/clang/0035-llvm-Do-not-use-standard-search-paths-in-find_librar.patch
- recipes-devtools/clang/common.inc
> nativesdk-clang: Fix build on hosts with older ncurses

- dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace_0.16.0.bb
Include segfault workaround for LLVM 15 OpaquePointers (a277ec4).
Signed-off-by: Michal Wojcik <michal.wojcik@linaro.org>
---
> bpftrace: Upgrade package to latest master (a277ec4)

- dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace/run-ptest
- dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace_0.16.0.bb
Hi @kraj,
bpftrace is now fully functional on master, so following your suggestions from https://github.com/kraj/meta-clang/pull/659 I'd like to add ptest support for it.
As expected not all tests pass, but it should be a good starting point to verify future fixes. I had to disable two runtime test suites as they hanged whole suite forever. Current results from poky master and qemuarm64:
```
root@qemuarm64:~# ptest-runner -t 2400 bpftrace
2022-09-30T08:31
BEGIN: /usr/lib/bpftrace/ptest
PASS: Unit test ast.
PASS: Unit test bpftrace.
PASS: Unit test bpftrace_btf.
PASS: Unit test childproc.
PASS: Unit test clang_parser.
PASS: Unit test clang_parser_btf.
PASS: Unit test LogStream.
PASS: Unit test Log.
PASS: Unit test Parser.
PASS: Unit test semantic_analyser.
PASS: Unit …
```
> bpftrace: Add ptest support

- dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace/run-ptest
- dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace_0.14.1.bb
Hi @kraj. I'd like to introduce ptest support for bpftrace and I'd like to hear your comments.
I had to start with kirkstone branch, because currently on master `bpftrace -info` segfaults (after 0.16.0 upgrade), so starting any test is not possible (I'll be working on that later).
Currently not all tests are passing, but it should be a good starting point to fix them. I also had to disable two runtime test suites as they hanged whole suite forever.
All tests may take up to 30 minutes, so running it with `ptest-runner -t 1800 bpftrace` is recommended.
Here is the ptest output this code produces:
```
root@qemuarm64:/# ptest-runner -t 1800 bpftrace
2022-09-16T13:32
BEGIN: /usr/lib/bpftrace/ptest
PASS: Unit test ast.
PASS: Unit test bpftrace.
PASS: Unit test bpftrace_btf. …
```
> bpftrace: Add ptest support (kirkstone)

- classes/clang.bbclass
- recipes-devtools/clang/clang_git.bb
Ensure that clang-tidy, clang-format, clang-tools are separated out into own packages and also move libclang-cpp shared object out of clang package too, which should remove every package depending on clang package since this shared object is needed by all tools.
Might fix https://github.com/kraj/meta-clang/issues/672
---
- '*Comment*' if you don't feel you have enough information to decide either …
> clang: Implement finer grained packaging

- conf/nonclangable.conf
compiler-rt does not provide the TF functions for x86 or x86_64 since it does not support TF functions on architectures which does not support 128-bit long double.
---
> fmt: Use libgcc on x86_64 as well

- dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc/ptest_wrapper.sh
- dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc/run-ptest
- dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc_0.25.0.bb
Hello @kraj, I added ptest support in bcc package reusing cc and python tests provided with the package. Lua tests are not included as they all fail on OE (and are also disabled in main repo).
Output from poky master on qemuarm64 and kernel built with `CONFIG_IKHEADERS=y`:
```
root@qemuarm64:~# ptest-runner -t 1800 bcc
2022-10-14T11:57
BEGIN: /usr/lib/bcc/ptest
PASS: cc language detection
PASS: cc shared object resolution
PASS: cc shared object resolution using loaded libraries
PASS: cc binary resolution with `which`
PASS: cc list all kernel symbols
PASS: cc file-backed mapping identification
PASS: cc resolve symbol name in external library
PASS: cc resolve symbol name in external library using loaded libraries
FAIL: cc resolve symbol addresses for a given PID
PASS: cc …
```
> bcc: Add ptest support

- dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace/run-ptest
- dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace_0.16.0.bb
I simplified script a little and used posix syntax for better compatibility as in bcc ptest suite. Additionally now there is no need for bash runtime dependency. 
Ptest output after changes:
```
root@qemuarm64:~# ptest-runner -t 3600 bpftrace
2022-10-20T13:10
BEGIN: /usr/lib/bpftrace/ptest
PASS: unit:ast.
PASS: unit:bpftrace.
PASS: unit:bpftrace_btf.
PASS: unit:childproc.
PASS: unit:clang_parser.
PASS: unit:clang_parser_btf.
PASS: unit:LogStream.
PASS: unit:Log.
PASS: unit:Parser.
PASS: unit:semantic_analyser.
PASS: unit:portability_analyser.
PASS: unit:portability_analyser_btf.
PASS: unit:procmon.
PASS: unit:probe.
PASS: unit:probe_btf.
PASS: unit:resource_analyser.
PASS: unit:required_resources.
PASS: unit:semantic_analyser_btf.
PASS: unit:semantic_analyser_dwarf. …
```
> bpftrace: Simplify ptest script and use posix syntax

- conf/nonclangable.conf
Use libgcc on x86 instead of compiler-rt
llvm objcopy errors out so disable it for now
Subprocess output:mips-yoe-linux-llvm-objcopy: error: Link field value 42 in section .rel.dyn is not a symbol table
--- …
> mybw: Use objcopy from binutils on mips

- conf/nonclangable.conf
Fixes
x86_64-yoe-linux-ld: /usr/src/debug/glibc/2.36-r0/stdio-common/printf_fphex.c:198: undefined reference to `__letf2' since compiler-rt does not provide the 'tf' functions
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but want to make …
> mybw: Use libgcc to link on x86_64

- conf/nonclangable.conf
> mybw: USe gnu objcopy on riscv64

- dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc/ptest_wrapper.sh
- dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc/run-ptest
- dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc_0.24.0.bb
- dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace/run-ptest
- dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace_0.14.1.bb
Commits cherry-picked without major conflicts.
ptest output:
```
2022-11-02T09:17
BEGIN: /usr/lib/bcc/ptest
PASS: cc language detection
PASS: cc shared object resolution
PASS: cc shared object resolution using loaded libraries
PASS: cc binary resolution with `which`
PASS: cc list all kernel symbols
PASS: cc file-backed mapping identification
PASS: cc resolve symbol name in external library
PASS: cc resolve symbol name in external library using loaded libraries
FAIL: cc resolve symbol addresses for a given PID
PASS: cc resolve symbols using /tmp/perf-pid.map
PASS: cc searching for modules in /proc/[pid]/maps
PASS: cc resolve global addr in libc in this process
PASS: cc get online CPUs
PASS: cc test array table
PASS: cc percpu array table
PASS: cc test bpf table
PASS: cc …
```
> bpftrace/bcc: backport ptest changes to kirkstone

- recipes-devtools/clang/clang/0037-sanitizer-Remove-include-linux-fs.h-to-resolve-fscon.patch
- recipes-devtools/clang/clang_git.bb
- recipes-devtools/clang/common.inc
- recipes-devtools/clang/compiler-rt-sanitizers_git.bb
Commits cherry picked from master:
*   3dd695755cda  compiler-rt-sanitizers: fix multiple installations for orc lib  
*   245e2346ab83  clang: Add compiler-rt and libcxx to build time depends for target  
*   79236c2f7b01   compiler-rt-sanitizer: fix nativesdk-compiler-rt-sanitizers build    
*   710434252979  sanitizer: Fix build with glibc 2.36 
To build compiler-rt and compiler-rt-sanitizer in SDK add in local.conf or in packagegroups:
```
TOOLCHAIN_HOST_TASK:append = "  nativesdk-compiler-rt  nativesdk-compiler-rt-sanitizers"   
TOOLCHAIN_TARGET_TASK:append = "  libcxx-dev libcxx-staticdev compiler-rt-dev compiler-rt-staticdev compiler-rt-sanitizers-dev compiler-rt-sanitizers-staticdev" 
```
To Test:
Tested for a simple program to check address sanitizer by evoking return after free: …
> compiler-rt-sanitizers: backport to build compiler-rt sanitizers

- recipes-devtools/clang/clang/0035-lldb-fix-swig-error.patch
- recipes-devtools/clang/clang/0036-dc8f6ffc3bf297098a1dfd3fbce801afbe9f5238.patch
- recipes-devtools/clang/common.inc
OE-core recently upgraded to swig 4.1.0 which results in errors:
11:49:31  | /poky/build/tmp/work-shared/llvm-project-source-15.0.4-r0/git/lldb/bindings/interfaces.swig:5: Error: Macro '__STDC_LIMIT_MACROS' redefined, 11:49:31  | :1: Error: previous definition of '__STDC_LIMIT_MACROS'.
Backport patches from release/15.x branch to fix these.
Signed-off-by: Anuj Mittal <anuj.mittal@intel.com>
---
- '*Comment*' if you don't feel you have enough …
> clang: backport patches to fix lldb errors

- conf/nonclangable.conf
Results in assembly file errors e.g.
| <instantiation>:1:1: error: unknown directive
| .func fname
| ^
| <instantiation>:2:1: note: while in macro instantiation | pixman_asm_function fname
| ^
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, …
> pixman: Do not use clang assembler for now

- conf/nonclangable.conf
Needed until [1] is merged into oe-core
[1] https://patchwork.yoctoproject.org/project/oe-core/patch/20221123215941.2411460-1-raj.khem@gmail.com/
---
> rsync: Use gcc for now

- recipes-devtools/clang/clang_git.bb
Ensure that lldb uses correct python-dev headers from target python and not native python during cross compile.
Adjust *_PYTHON_* variables accordingly.
---
> clang: Inherit python3targetconfig

- recipes-devtools/clang/clang/0035-cmake-Enable-64bit-off_t-on-32bit-glibc-systems.patch
- recipes-devtools/clang/common.inc
Ensures that correct cmake checks are used to enable LFS64
---
> clang: Fix build with LFS64 on musl

- conf/nonclangable.conf
Make path to OBJCOPY correct for linux-yocto package. Use gcc for now for erlang and pciutils.
Signed-off-by: Aleksey Smirnov <aleksey.smirnov@yadro.com>
---
Backport of #698, for kirkstone
> objcopy: fix path for RISC-V

- conf/nonclangable.conf
Add "erlang" for all architectures (found on riscv64 and x86-64) Add "grub" for x86-64 architecture
Use proper OBJCOPY for "linux-yocto" for all architectures
Signed-off-by: Aleksey Smirnov <aleksey.smirnov@yadro.com>
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently …
> nonclangable.conf: Add new exceptions

- recipes-devtools/clang/openmp_git.bb
When built with thin LTO enabled, LLVM produces object files containing LLVM IR, which ld can't understand. Since we're forcing the toolchain to clang anyway, let's also force using lld.
I was supposed to make this patch against master, but I can not reproduce it there, and my machine is too weak to repeatedly rebuild various clang versions in a reasonable time.
---
- '*Comment*' if you don't feel you have enough information to decide either …
> Fix OpenMP builds with thin LTO enabled.

- conf/nonclangable.conf
- recipes-core/systemd/systemd_%.bbappend
Fixes
/usr/bin/mybw', 'TOPDIR/build/tmp/work/riscv32-yoe-linux/mybw/0.0+gitAUTOINC+f4bdeee126-r0/package/usr/bin/.debug/mybw']' returned non-zero exit status 1. Subprocess output:riscv32-yoe-linux-llvm-objcopy: error: Link field value 37 in section .rela.dyn is not a symbol table
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, …
> mybw: Use gnu objcopy on rv32

- conf/nonclangable.conf
Some upgrades have regressed pixman with clang on aarch64, until this is sorted, lets use gcc for it as a workaround
---
> pixman: Use gcc on aarch64

- recipes-devtools/clang/openmp_git.bb
The /usr/lib/libomptarget.devicertl.a static library ends up with build paths embedded.  The CMake files don't respect our CXXFLAGS so don't use the -fdebug-path-map arguments, but even adding those didn't solve it: it looks like code via goes via LLVM bytecode files doesn't get remapped?
Until that is solved, skip the buildpath check.
Signed-off-by: Ross Burton <ross.burton@arm.com>
> openmp: skip buildpaths QA check for openmp-staticdev

- recipes-devtools/clang/clang/0036-libc-LWG2993-reference_wrapper-T-conversion-from-U.patch
- recipes-devtools/clang/common.inc
Fixes:
../../chrome/common/extensions/chrome_manifest_url_handlers.cc:101:7:
error: no matching constructor for initialization of 'std::map<const char *, std::reference_wrapper<const absl::optionalstd::string>>' (aka 'map<const char , reference_wrapper<const optional<basic_string>>>')
std::map<const char,
as seen with chromium-109:
https://github.com/OSSystems/meta-browser/issues/674
Thanks to Raphael Kubo da Costa for finding the commit to be backported!
Signed-off-by: Randy MacLeod <Randy.MacLeod@windriver.com>
---
- '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that …
> Backport fix for no matching constructor

- conf/nonclangable.conf
- recipes-devtools/clang/libcxx_git.bb
- recipes-devtools/clang/openmp_git.bb
This helps statically linking c++ runtime into binaries which use exceptions functions e.g. std::out_of_range as used in rwmem package and using -static-libstdc++ compiler flags
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but want to …
> libcxx: Build libc++abi into static libc++.a

- recipes-devtools/clang/llvm-project-source.inc
This if a follow-up of the gcc-source in oe-core [1] and this will fix this recipe when used with multiconfig machines in a way that it can be reused between the machines.
[1] https://git.yoctoproject.org/poky/commit/?id=2cdaa164e8b4618a82ccd3fcb87cf58e36b6d6d3
Signed-off-by: Jose Quaresma <jose.quaresma@foundries.io>
---
- [x ] `Signed-off-by` is present
- [x ] The PR complies with the [Open Embedded Commit Patch Message Guidelines](http://www.openembedded.org/wiki/Commit_Patch_Message_Guidelines)
- '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, …
> llvm-project-source: Ensure sstate hash doesn't change

- recipes-devtools/clang/clang_git.bb
when building clang for multilib, bitbake complains about liblldb containing a .so symlink
this patch fixes this
Signed-off-by: lumpyh <lumpy.hega@gmx.de>
---
> clang: fix clang recipe for multilib build

- recipes-devtools/clang/openmp_git.bb
Enable ompd gdb plugin build and add py3 to depndencies as it is required by the plugin
---
> openmp: Provide missing tools during cross compile

- recipes-graphics/mesa/mesa_%.bbappend
Change mesa bbappend to override PACKAGECONFIG[gallium-llvm] only if clang toolchain is selected. Unfortunately this has to be implemented in a nasty way because there is no standard way to apply override to the variable flag setting.
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but …
> mesa: don't override PACKAGECONFIG[gallium-llvm] in non-clang case

- recipes-devtools/clang/openmp_git.bb
> openmp: Fix build with 64bit file offset on 32bit arches

- recipes-devtools/bindgen-cli/bindgen-cli_0.64.0.bb
It is used by Mesa to build Rusticl.
---
> bindgen-cli: New recipe for version 0.64.0

- recipes-devtools/clang/clang/0031-libc-LWG2993-reference_wrapper-T-conversion-from-U.patch
- recipes-devtools/clang/common.inc
Hi everyone
I had the same issue which was mentioned here: https://github.com/OSSystems/meta-browser/issues/674 and then fixed for dunfell in this pull request [!728](https://github.com/kraj/meta-clang/pull/728) on kirkstone. Applying the same patch in kirkstone-clang12 fixed the problem for me.
Thanks to [@rwmacleod](https://github.com/rwmacleod) for the original pull request.
> kirkstone-clang12 Backport fix for no matching constructor

- recipes-devtools/bindgen-cli/bindgen-cli-crates.inc
- recipes-devtools/bindgen-cli/bindgen-cli_0.64.0.bb
> bindgen-cli: Add missing SRC_URI sha256sum for all dependency crates

- conf/nonclangable.conf
This reverts commit 20a8cff8ba0ce02773946cd7ba398fc08969ce1e.
---
> Revert "webkitgtk: Use gcc for now"

- recipes-devtools/clang/compiler-rt_git.bb
It fails to run task do_package of compiler-rt with [installed-vs-shipped] issue when ${libdir} does not equal ${nonarch_libdir}. Update do_install script to fix the issue.
---
> compiler-rt: fix installed-vs-shipped qa issue

- recipes-devtools/bindgen-cli/bindgen-cli-crates.inc
- recipes-devtools/bindgen-cli/bindgen-cli_0.64.0.bb
* it's needed for compatibility with updated fetcher from: https://patchwork.yoctoproject.org/project/bitbake/patch/20230405122125.3358972-1-enrico.scholz@sigma-chemnitz.de/
---
> bindgen-cli: regenerate with updated bbclass

- recipes-devtools/clang/clang_git.bb
* The perl scan-build script need some perl-modules to be executable
---
Missing perl modules runtime dependencies causes errors when executing perl scan-build script. For example:
```shell
`Can't locate FindBin.pm …
```
> Add missing scan-build runtime dependencies

- recipes-devtools/clang/clang_git.bb
---
Missing perl modules runtime dependencies causes errors when executing perl scan-build script. For example:
```shell
`Can't locate FindBin.pm in @INC (you may need to install the FindBin module) (@INC contains: …
```
> Add missing scan-build runtime dependencies (dunfell)

- recipes-devtools/clang/clang/0037-clang-Call-printName-to-get-name-of-Decl.patch
- recipes-devtools/clang/common.inc
Clang gives a name to the constructors of anonymous structures in debug info that's based on the filename of the structure's definition. It didn't respect the debug-prefix-map setting, causimg QA warnings in several recipes, notably libcxx.
--- …
> clang: fix reproducibily issue

- recipes-devtools/clang/clang-cross-canadian_git.bb
- recipes-devtools/clang/clang-crosssdk_git.bb
- recipes-devtools/clang/clang_git.bb
> Drop crosssdk suffix from virtual binutils provides to match oe-core

- recipes-devtools/clang/clang_git.bb
Hi, LLVM officially supports LoongArch starting from 16.0.0, we can add its support to meta-clang now.
> LLVM officially supports LoongArch starting from 16.0.0

- conf/nonclangable.conf
e.g. -msha will otherwise be deemed available when using clang which is not correct, therefore treat unused-command-line-argument as error which will be flagged on non-x86 arches
---
> btrfs-tools: Error out on x86 options on non-x86 arches

- recipes-devtools/clang/clang/llvm-config
--libfiles        Fully qualified library filenames for makefile depends.
This option is being used by ispc cmake.
https://github.com/ispc/ispc/blob/main/cmake/FindLLVM.cmake#L116
---
> llvm-config: add --libfiles option

- recipes-graphics/mesa/mesa_%.bbappend
This bbappend is now just:
YOCTO_ALTERNATE_EXE_PATH:toolchain-clang = "${STAGING_LIBDIR}/llvm-config" YOCTO_ALTERNATE_EXE_PATH:toolchain-clang = "1"
This results in YOCTO_ALTERNATE_EXE_PATH being "1". The second line is clearly a typo, so if we remove this then it changes the path from STAGING_BINDIR (as set in clang.bbclass) to STAGING_LIBDIR. If this is the correct change to make then it should be done in clang.bbclass instead.
Also, the only place that YOCTO_ALTERNATE_EXE_PATH is respected is as an environment variable, and this is never exported. It is likely that the second line was meant to end [export] = "1".
This parameter appears to be no longer needed, so remove the append.
> mesa: remove bbappend

- classes/clang.bbclass
Create a symbolic link lld -> ld in recipe sysroot to choose the default linker lld when ld-is-lld is set in DISTRO_FEATURES. othereise, we can get linking issues when '-fuse-ld=lld' is in LDFLAGS but the actual ld is not lld.
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but want to …
> clang.bbclass: create lld symbolic link in sysroot when ld-is-lld is set

- conf/layer.conf
- conf/nonclangable.conf
- recipes-devtools/clang/clang.inc
This is required with clang after the assembly file is added which uses these instructions. it works with gcc because it uses .option directive to enable zbb extentions in toolchain on the fly clang does not have similar option
| <instantiation>:6:21: warning: unknown option, expected 'push', 'pop', 'rvc', 'norvc', 'relax' or 'norelax'
|             .option arch, +zbb
This fixes
| src/libavcodec/riscv/bswapdsp_rvb.S:61:9: error: instruction requires the following: 'Zbb' (Basic Bit-Manipulation) or 'Zbkb' (Bitmanip instructions for Cryptography)
|         rev8 t0, t0
|         ^
---
- '*Request Changes*' if this …
> ffmpeg: Enable zbb manip extensions for rv32/rv64

- README.md
- conf/layer.conf
- recipes-devtools/clang/clang_git.bb
Document a way to enable it per distro. This helps this layer pass the yocto check layer test
---
> clang: Do not provide llvm-native implicitly

- dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc_0.26.0.bb
the upstream changed the shebang of python scripts in tools folder[1], this would cause do_install:append cannot conver all scripts.
[1] https://github.com/iovisor/bcc/commit/3f5e402bcadf44ce0250864db52673bf7317797b
--- …
> bcc: updating the shebang of python scripts in tools to python3

- recipes-devtools/clang/clang/0038-clang-Apply-fmacro-prefix-map-to-anonymous-tags-in-t.patch
- recipes-devtools/clang/common.inc
This fixes real file names appearing in lambda names that are used as arguments to function templates.
This fixes llvm/llvm-project#63219, which I spotted when building cmake.
---
> clang: Apply upstream D152570

- recipes-devtools/clang/clang/0038-Add-missing-cstdint.patch
- recipes-devtools/clang/common.inc
---
- [ x ] Changes have been tested
- [ x ] `Signed-off-by` is present
- [ x ] The PR complies with the [Open Embedded Commit Patch Message Guidelines](http://www.openembedded.org/wiki/Commit_Patch_Message_Guidelines) …
> [kirkstone] clang: fix build with yocto uninative gcc 13

- recipes-devtools/clang/clang/llvm-config
From multilib build:
| CMake Error at cmake/FindLLVM.cmake:79 (message):
|   Failed running
|  tmp-glibc/work/x86-64-v3-oe-linux/ispc/1.20.0-r0/recipe-sysroot/usr/bin/crossscripts/llvm-config;--libfiles;engine;ipo;bitreader;bitwriter;instrumentation;linker;option;frontendopenmp;windowsdriver;x86
| Call Stack (most recent call first):
|   cmake/FindLLVM.cmake:116 (run_llvm_config)
|   CMakeLists.txt:377 (get_llvm_libfiles)
Currently hardcoded to /lib, which causing multilib build failure.
An easy solution could be set and export YOCTO_ALTERNATE_LIBDIR to $baselib in recipe, but it would require to add this in all affected recipes.
Other approach is to handle in llvm-config script itself. Unfortunately $baselib is not available in env for the llvm-config script, so extracting baselib value …
> llvm-config: fix script for multilib build

- dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace/0001-Adjust-to-build-with-llvm-17.patch
- dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace/0001-cmake-Raise-max-llvm-major-version-to-16.patch
- dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace_0.18.0.bb
> update bpftrace to 0.18.0

- dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc_0.28.0.bb
examples/tracing/nflatency.py has already upgraded the shebang to python3 on upstream, so when we apply the do_install:append function, the shebang of nflatency.py become /usr/bin/env python33
---
> bcc: fix some of python script with wrong shebang

- dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace_0.18.0.bb
Building bpftrace tests after upgrade requires pahole and llvm-objcopy.
Otherwise do_configure fails with errors:
```
| CMake Error at tests/data/CMakeLists.txt:5 (find_program):
|   Could not find PAHOLE using the following names: pahole
| CMake Error at tests/data/CMakeLists.txt:6 (find_program):
|   Could not find LLVM_OBJCOPY using the following names: llvm-objcopy,
|   llvm-objcopy-16, llvm16-objcopy
```
---
- '*Comment*' if you don't …
> bpftrace: Fix v0.18.0 build with PTEST_ENABLED

- recipes-devtools/clang/clang_git.bb
Fixes
ERROR: lib32-clang-15.0.7-r0 do_package_qa: QA Issue: non -dev/-dbg/nativesdk- package lib32-liblldb contains symlink .so '/usr/lib/liblldbIntelFeatures.so'
non -dev/-dbg/nativesdk- package lib32-liblldb contains symlink .so '/usr/lib/liblldb.so' [dev-so]                                                                                      ERROR: lib32-clang-15.0.7-r0 do_package_qa: Fatal QA errors were found, failing task.
I know langdale is out of support, but if you can apply this simple backport it will keep my CI world builds a bit happier, thanks.
> clang: Move .so symlinks to -dev package fixes multilib build

- recipes-devtools/clang/libclc_git.bb
It pokes at target llvm.cmake and gets the path
LLVM_TOOLS_BINARY_DIR pointing to target sysroot
however during cross builds it should be looking
for tools for cross building in native sysroot
MJ: otherwise it may fail to build with gold linker:
DWARF error: invalid or unhandled FORM value: 0x23
> libclc: Define llvm tools needed during build

- .github/workflows/yoe.yml
- conf/nonclangable.conf
> Fix elfutils and gnu-efi build with LLD linker

- conf/nonclangable.conf
This ends up with compile errors when using clang compiler, therefore internal assembler is disabled with qt6
---
> qtbase: Do not use internal assembler with clang

- conf/nonclangable.conf
- systemd-boot have it fixed on recipe but as it a clang issue it's better to move it here
- systemd needs it when build with efi package config enabled since v254
---
> nonclangable.conf: fix systemd efi build

- recipes-devtools/clang/llvm-project-source.inc
MULTILIBS maybe defined by distros/projects and in some cases not, this would result in rebuilding clang-native for no reason.
---
> llvm-project-source: Remove "MULTILIBS" from do_patch dependecies

- conf/nonclangable.conf
clang 15+ has started to treated int-conversion as error and pipeline cache code added snippets[1] in gtk4 which causes this error
[1] https://gitlab.gnome.org/GNOME/gtk/-/commit/684a015c9852ede9d57103852217b428546fe472
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently …
> gtk4: Disable integer conversion warning as error

- conf/nonclangable.conf
go linker is not able to link subsequent binaries e.g. gosu with lld produced libstd.so and crashes. This is just seen on arm64
---
> go-runtime: Use BFD linker when LLD is default system linker on aarch64

- recipes-devtools/python/python3_%.bbappend
cppext test needs full toolchain as it tries to build an extention with C, using clang ensures that a function
compiler bits are pulled into ptest image when using TOOLCHAIN = "clang"
---
> python3: Add clang to rdeps for python3-ptests

- conf/nonclangable.conf
It uses symbol versioning like xyz@@ which lld does not like see https://github.com/llvm/llvm-project/issues/65017
---
> libfaketime: Use BFD linker when LLD is system default

- recipes-devtools/clang/clang/0006-clang-driver-Check-sysroot-for-ldso-path.patch
- recipes-devtools/clang/clang/0017-clang-driver-Add-dyld-prefix-when-checking-sysroot-f.patch
- recipes-devtools/clang/clang/0040-ToolChains-Gnu.cpp-ARMLibDirs-search-also-in-lib32.patch
- recipes-devtools/clang/common.inc
* in some strange multilib configs we build lib32-image where 32bit libs are in /usr/lib32 and 64bit in /usr/lib64 but in such setup the clang search for GNU candidate installation doesn't check lib32 directory in sysroot and fails to find the installation there resulting in
lib32-compiler-rt build failure:
```
-- Configuring incomplete, errors occurred!
CMake Error at TOPDIR/BUILD/work/raspberrypi4_64-oemllib32-linux-gnueabi/lib32-compiler-rt/16.0.6/recipe-sysroot-native/usr/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:67 (message):
The C compiler
"TOPDIR/BUILD/work/raspberrypi4_64-oemllib32-linux-gnueabi/lib32-compiler-rt/16.0.6/recipe-sysroot-native/usr/bin/arm-oemllib32-linux-gnueabi/arm-oemllib32-linux-gnueabi-clang"
is not able to compile a simple test program.
It fails with …
```
> clang: ToolChains/Gnu.cpp: search also in lib32

- dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace_0.18.0.bb
The issue has been fixed upstream
---
> bpftrace: Build tests for rv64 again

- recipes-devtools/clang/clang_git.bb
These tools are only needed during build and we are using them from clang-native, so they are not needed to be either built or packages in nativesdk-clang or target clang builds
Fixes Issue #859
---
> clang: Do not package tablegen built during cross-compile

- conf/nonclangable.conf
This recipe got renamed in oe-core, it still is glibc based and can not be built with clang yet
---
> nonclangable: Adjust for glibc-tests -> glibc-y2038-tests rename

- conf/nonclangable.conf
These functions are unconditionally added to libcgroup.map Fixes
aarch64-yoe-linux-musl-ld.lld: error: version script assignment of 'CGROUP_3.0' to symbol 'cgroup_create_scope' failed: symbol not defined aarch64-yoe-linux-musl-ld.lld: error: version script assignment of 'CGROUP_3.0' to symbol 'cgroup_set_default_scope_opts' failed: symbol not defined aarch64-yoe-linux-musl-ld.lld: error: version script assignment of 'CGROUP_3.0' to symbol 'cgroup_create_scope2' failed: symbol not defined aarch64-yoe-linux-musl-ld.lld: error: version script assignment of 'CGROUP_3.0' to symbol 'cgroup_write_systemd_default_cgroup' failed: symbol not defined
---
- '*Approve*' if this change would be acceptable in the codebase (even if there are minor or cosmetic …
> libcgroup: Use --undefined-version with lld on sysvinit

- recipes-devtools/clang/common-source.inc
- recipes-devtools/clang/llvm-project-source.inc
- recipes-devtools/clang/nativesdk-clang-glue.bb
Backport commits from master fixing the circular dependency problem when using spdx bbclass.
- [nativesdk-clang-glue: delete spdx tasks](https://github.com/kraj/meta-clang/commit/43b8519600c9e08bcbd921569c8533151f630bd6)
- [llvm-project-source: fix create-spdx handling](https://github.com/kraj/meta-clang/commit/509be6044027806d87f0b1c0aa02fcbab2642023)
- [common-source: fix create-spdx handling](https://github.com/kraj/meta-clang/commit/49b5b74bddb0b68edbfaf76d9ad99e086b3782de)
> Backporting spdx fixes

- classes/clang.bbclass
A pair of '[]' is missing, add them in.
---
> clang.bbclass: fix a typo

- recipes-devtools/clang/clang_git.bb
> Fix packaging error for libclang on kirkstone

- conf/nonclangable.conf
The optee-os and optee-os-tadevkit are available not only for tegra so it should be better to use a `:tegra` machine override there for all of the them.
---
> nonclangable: Make tegra specific packages only for tegra

- classes/clang.bbclass
So far when using toolchain = clang would punt gcc from native-sysroot but its beneficial to keep both compilers since they can co-exist its not a big problem to have both in sysroot. This helps in debugging issues as well.
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but want to …
> clang.bbclass: Stage along with gcc toolchain

- classes/cmake-native.bbclass
These variables show up as dependencies of native recipes otherwise can cause clang-native to rebuild without a reason just when defined by a machine using ubifs.
---
> cmake-native.bbclass: Add ubfs specific variable to ignore list

- classes/cmake-native.bbclass
The problem is in BSP layer [1], these variable should not be exported universally moreover its not needed as well.
[1] https://github.com/varigit/meta-variscite-bsp-imx/pull/36 This reverts commit 288f752445d3783dbaf06a60919a2b35b14e3a62.
--- …
> Revert "cmake-native.bbclass: Add ubfs specific variable to ignore list"

- recipes-devtools/clang/clang/0038-lldb-Get-rid-of-__STDC_LIMIT_MACROS-and-__STDC_CONST.patch
- recipes-devtools/clang/clang/0039-lldb-Fix-error-non-const-lvalue.-caused-by-SWIG-4.1..patch
- recipes-devtools/clang/common.inc
LLDB can't be built using kirkstone poky (swig 4.0.2) and current kirkstone clang 14.0.6, because of compiler error mentioned in patches
---
> clang-native: fix swig binding generation

- conf/nonclangable.conf
- recipes-connectivity/openssl/openssl_%.bbappend
> Use clang to compile openssh now

- dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace/0001-replace-python-with-python3-in-the-test.patch
- dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace_0.18.0.bb
"runtime:call" in ptest gets the following FAILED: | python: No such file or directory
Replace python with python3 in this ptest item.
---
- [ x] The PR complies with the [Open Embedded Commit Patch Message Guidelines](http://www.openembedded.org/wiki/Commit_Patch_Message_Guidelines)
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you …
> bpftrace: Replace python with python3 in ptest

- dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace_0.18.0.bb
"runtime:regression" in ptest gets the following FAILED: | nm: ./testprogs/uprobe_test: no symbols
Keep the debug info of uprobe_test to pass this ptest item.
the steps to repruduce:
$export BPFTRACE_RUNTIME_TEST_EXECUTABLE=/usr/bin
$cd /usr/lib/bpftrace/ptest/tests
$python3 runtime/engine/main.py --filter="regression.*" ***
| [  FAILED  ] regression.address_probe_invalid_expansion | 	Command: /usr/bin/bpftrace -e "uprobe:./testprogs/uprobe_test:0x$
|           (nm ./testprogs/uprobe_test | awk '$3 == "function1"
|           {print $1}') { @[probe] = count(); exit() }"
| 	Unclean exit code: 1
| 	Output: nm: ./testprogs/uprobe_test: no symbols\nNo probes to attach\n
***
---
- [ x] The PR complies with the [Open Embedded …
> bpftrace: Do not strip uprobe_test

- recipes-devtools/clang/clang/llvm-config
The Mesa Clover meson.build script passes two options to llvm-config script, --libs --ldflags. The script from meta-clang passes control to the native llvm-config script, which unfortunately results in the native dynamic linker option leaking to the cross build. Fix that by adopting the approach from OE-core and filter known options before calling into the native llvm-config.
---
- '*Comment*' if you don't feel you have enough information to …
> llvm-config: update following the oe-core script

- recipes-devtools/clang/clang_git.bb
Commit 79169d9 fixed non existing libclang package, but only libclang symlink was packaged. Use `libclang.so.*` wildcard to also include the shared library without hardcoding its version.
Before:
```
$ dpkg -c ./tmp/deploy/ipk/cortexa57/libclang_14.0.6-r0_cortexa57.ipk
drwxr-xr-x root/root         0 2011-04-06 01:00 ./usr/
drwxr-xr-x root/root         0 2011-04-06 01:00 ./usr/lib/
lrwxrwxrwx root/root         0 2011-04-06 01:00 ./usr/lib/libclang.so.13 -> libclang.so.14.0.6
```
After:
```
$ dpkg -c ./tmp/deploy/ipk/cortexa57/libclang13_14.0.6-r0_cortexa57.ipk
drwxr-xr-x root/root         0 2011-04-06 01:00 ./usr/
drwxr-xr-x root/root         0 2011-04-06 01:00 ./usr/lib/
lrwxrwxrwx root/root         0 2011-04-06 01:00 ./usr/lib/libclang.so.13 -> libclang.so.14.0.6
-rwxr-xr-x root/root …
```
> kirkstone: Fix libclang package files list

- recipes-devtools/valgrind/valgrind_%.bbappend
This should fix the layer check runs.
---
> valgrind: Cover do_install_ptest bbappend under clang override

- dynamic-layers/meta-python/recipes-devtools/bcc/bcc_0.28.0.bb
distutils package no longer exists after python 3.12 upgrade.
I haven't run ptest for this, but at least it will parse well now instead of:
ERROR: Nothing RPROVIDES 'python3-distutils' (but meta-clang/dynamic-layers/meta-python/recipes-devtools/bcc/bcc_0.28.0.bb RDEPENDS on or otherwise requires it)
> bcc: drop python3-distutils runtime dependency

- conf/nonclangable.conf
This fails to build otherwise
x86_64-yoe-linux-ld.lld: error: version script assignment of 'LIBCXL_3' to symbol 'cxl_mapping_get_region' failed: symbol not defined
---
> ndctl: Add --undefined-version with lld

- dynamic-layers/openembedded-layer/recipes-devtools/bpftool/bpftool.bbappend
Provides libLLVM when using clang
---
> bpftool: Add dependency on clang-libllvm

- recipes-devtools/clang/clang/0035-libcxx-Implement-LWG3545-std-pointer_traits-should-be-.patch
- recipes-devtools/clang/common.inc
Nanbield backport of #913.
---
> Backport "std::pointer_traits should be SFINAE-friendly"

- recipes-devtools/clang/compiler-rt-sanitizers_git.bb
While building compiler-rt-sanitizers I encountered some build and packaging issues. I am not certain why the missing `compiler-rt` dependency was not observed before but the configuration failure is reproducible in a clean Yocto build which merely includes the `meta-clang` layer without making any further configuration adaptations.
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major …
> compiler-rt-sanitizers: Build fixes

- recipes-devtools/clang/clang_git.bb
clangd should not be needed in target builds. Extend PACKAGECONFIG to
enable selective disabling and disable it by default for target builds.
Additionally, this enables compilation of `clang-native` on Debian "bullseye"
hosts where GCC 10 fails to compile clangd with an internal compilation
error.
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the …
> clang: Allow conditional compilation of clangd

- conf/nonclangable.conf
- recipes-devtools/rpm/rpm_%.bbappend
> Use gcc for rpm and fix dav1d on rv64

- conf/nonclangable.conf
Fixes
aarch64-yoe-linux-ld.lld: error: version script assignment of 'OPENLDAP_2.200' to symbol 'ldap_host_connected_to' failed: symbol not defined /error:       [1/17]
---
> openldap: Fix build with lld linker

- conf/layer.conf
- conf/nonclangable.conf
- recipes-devtools/clang/clang.inc
> clang: Bump version to 18.1.1

- conf/nonclangable.conf
There is a gir generation error when compiled with clang
| /mnt/b/yoe/master/build/tmp/work/core2-64-yoe-linux-musl/gtk4/4.12.5/recipe-sysroot/usr/include/glib-2.0/gobject/gobject.h:822: syntax error, unexpected INTEGER, expecting identifier in '  do
{ if (__builtin_expect (__extension__ ({ int G_PASTE (_g_boolean_var_, 9); if ((weak_pointer) == ((void*)0)) G_PASTE (_g_boolean_var_, 9) = 1; else G_PASTE (_g_boolean_var_, 9) = 0; G_PASTE (_
g_boolean_var_, 9); }), 1)) ; else g_assertion_message (((gchar*) 0), "/mnt/b/yoe/master/build/tmp/work/core2-64-yoe-linux-musl/gtk4/4.12.5/recipe-sysroot/usr/include/glib-2.0/gobject/gobject.h ", 822, ((const char*) (__func__)), "'" "weak_pointer" "' should be NULL"); } while (0);' at '9' | /mnt/b/yoe/master/build/tmp/work/core2-64-yoe-linux-musl/gtk4/4 …
> gtk4: Compile with gcc for musl/x86_64

- dynamic-layers/meta-python/recipes-devtools/bcc/bcc_0.29.1.bb
Current LUAJIT actually not works, below is snip of src/lua/CMakeLists.txt
[snip]
find_package(LuaJIT)
find_program(LUAJIT luajit)
if (LUAJIT_LIBRARIES AND LUAJIT)
FILE(GLOB_RECURSE SRC_LUA
${CMAKE_CURRENT_SOURCE_DIR}/bcc/*.lua
${CMAKE_CURRENT_SOURCE_DIR}/bcc/vendor/*.lua
${CMAKE_CURRENT_SOURCE_DIR}/bpf/*.lua)
ADD_CUSTOM_COMMAND(
OUTPUT bcc.lua
COMMAND ${LUAJIT} ${CMAKE_CURRENT_SOURCE_DIR}/src/squish.lua ${CMAKE_CURRENT_SOURCE_DIR}
DEPENDS ${SRC_LUA} ${CMAKE_CURRENT_SOURCE_DIR}/squishy
)
ADD_CUSTOM_COMMAND(
OUTPUT bcc.o
COMMAND ${LUAJIT} -bg bcc.lua bcc.o
DEPENDS bcc.lua
)
[snip]
LUAJIT will be set when luajit is found. For oe, maybe we need to
DEPENDS on luajit-native. But there are still 2 problems after I change
DEPENDS from luajit to luajit-native and export …
> bcc: remove LUAJIT setting and related examples

- conf/layer.conf
Downstream projects need time to switch to opaque
pointers in llvm16 which requires in some cases
significant effort.
> layer.conf: Mark it scarthgap compatible

- classes/clang.bbclass
This avoids qtwebengine crashes on rpi4/rpi3
---
> clang: Use +nocrypto with -mcpu for rpi3/rpi4

- conf/nonclangable.conf
> elfuitls: add unused-const-variable fix

- conf/nonclangable.conf
This reverts commit 81e5f4eef93b5e1d6507daaf74fce28a2ccd7cf7.
It is merged in oe-core master
---
> Revert "nonclangable: elfuitls: add unused-const-variable fix"

- dynamic-layers/qt6-layer/recipes-qt/qt6/qttools_%.bbappend
clang dependency is already added in meta-qt6 recipe.
---
> qt6/qttools: remove bbappend

- conf/nonclangable.conf
2.5+ does not link with lld as it has some linker script magic for versioned symbols
---
> liburing: Use --undefined-version with lld

- recipes-devtools/clang/common.inc
Align the source url with oe-core
(meta/recipes-devtools/llvm/llvm_git.bb)
Currently when creating shallow tarball download mirror one of the biggest files is llvm and it has to be stored twice because of this difference.
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but want to make …
> clang: add .git to repository source url

- conf/layer.conf
- recipes-devtools/clang/clang.inc
Brings
* 617a15a9eac9 [clang codegen] Fix MS ABI detection of user-provided constructors. (#90151)
* 20b9ed64ea07 [RISCV][ISel] Fix types in `tryFoldSelectIntoOp` (#90659)
* ece9d35f1a70 [GlobalISel] Fix store merging incorrectly classifying an unknown index expr as 0. (#90375)
* a7b8b890600a [X86] Enable EVEX512 when host CPU has AVX512 (#90479)
* 4da5b1417493 [GlobalISel] Don't form anyextending atomic loads.
* a96b04442c9f [AArch64] Remove invalid uabdl patterns. (#89272)
* aea091b70eda [clang][CoverageMapping] do not emit a gap region when either end doesn't have valid source locations (#89564)
* 58648f334d62 [X86][EVEX512] Check hasEVEX512 for canExtendTo512DQ (#90390)
* 6350acdb134d  [CGP] Drop poison-generating flags after hoisting (#90382)
* f341c76b9461 [Clang] Handle structs …
> clang: Upgrade to 18.1.5

- conf/nonclangable.conf
symbol version script adds some X11 symbols which lld complains about since default is to report undefined symbols with lld.
Fixes
| x86_64-yoe-linux-ld.lld: error: version script assignment of 'FRAME_2.2' to symbol 'frame_x11_new' failed: symbol not defined | x86_64-yoe-linux-ld.lld: error: version script assignment of 'FRAME_2.2' to symbol 'frame_x11_delete' failed: symbol not defined | x86_64-yoe-linux-ld.lld: error: version script assignment of 'FRAME_2.2' to symbol 'frame_x11_process_event' failed: symbol not defined | x86_64-yoe-linux-ld.lld: error: version script assignment of 'FRAME_2.2' to symbol 'frame_x11_accept_touch' failed: symbol not defined | x86_64-yoe-linux-ld.lld: error: version script assignment of 'FRAME_2.2' to symbol 'frame_x11_reject_touch' failed: symbol not …
> frame: Use --undefined-version with lld

- recipes-devtools/clang/clang.inc
- recipes-devtools/clang/common.inc
For clang 18.1.5, the llvm-project-source repository is about 3GB big, whereas the source tarball is 126MB big. Using the source tarball instead of the git repository speeds up the fetch step significantly.
Also, the git repository is getting so big that depending on the network setup, it is necessary to change git http.postBuffer options in order to avoid errors such as "fetch-pack: unexpected disconnect while reading sideband packet".
---
- …
> clang: use release tarball instead of git

- conf/layer.conf
oe-core switched to styhead in: https://git.openembedded.org/openembedded-core/commit?id=cef91ebeb3f2b1d41336fff60555064430a80397
---
> layer.conf: update LAYERSERIES_COMPAT for styhead

- recipes-devtools/spirv-llvm-translator/spirv-llvm-translator_git.bb
This brings specifically this commit
Remove dependency on SPIRV-Headers for SPV_INTEL_maximum_registers
Which is needed to fix build errors with bump to 18.1.0
---
> spirv-llvm-translator: Bump spirv-headers to matching tag

- recipes-devtools/spirv-llvm-translator/spirv-llvm-translator_git.bb
* just one extra commit:
spirv-llvm-translator-native/18.1.0/git $ git log --oneline ad99707fd80189dca0ca76ed89946ae383e9a030..16b2900747a3cc7993eeb39d4a8442b432a3fda0
16b29007 [LLVM-18] Remove dependency on SPIRV-Headers for SPV_INTEL_maximum_registers (#2434)
* fixes: http://errors.yoctoproject.org/Errors/Build/185272/
spirv-llvm-translator-native/18.1.0/git/lib/SPIRV/libSPIRV/SPIRVEnum.h:295:17: error: ‘CapabilityRegisterLimitsINTEL’ was not declared in this scope
295 |                {CapabilityRegisterLimitsINTEL});
|                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> spirv-llvm-translator: bump SRCREV to fix the build

- conf/layer.conf
- recipes-devtools/clang/clang.inc
- recipes-devtools/clang/common.inc
* 768118d1ad38 [clang-format] Fix a bug in formatting goto labels in macros (#92494)
* 8c0fe0d65ed8 release/18.x: [clang-format] Don't always break before << between str… (#94091)
* 7e6ece9b4f2d [PPCMergeStringPool] Only replace constant once (#92996)
* 1ce2d26cd2e9 Bump version to 18.1.7 (#93723)
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the …
> clang: Upgrade to 18.1.7

- recipes-devtools/clang/clang_git.bb
This ensures that nativesdk compiler can be built when DEBUG_BUILD = "1"
Fixes https://github.com/kraj/meta-clang/issues/932
---
> clang: Disable unused-command-line-argument warning for debug builds

- 0001-bpftrace-fix-CVE-2024-2313.patch
If kernel headers need to be extracted, bpftrace will attempt to load them from a temporary directory. An unprivileged attacker could use this to force bcc to load compromised linux headers. Linux distributions which provide kernel headers by default are not affected by default.
> bpftrace: fix CVE-2024-2313.patches via upload

- conf/layer.conf
- recipes-devtools/clang/clang.inc
- recipes-devtools/clang/common.inc
Brings
* 3b5b5c1ec4a3 [libcxx] Align `__recommend() + 1`  by __endian_factor (#90292)
* 72c9425a79fd [libc++][NFC] Rewrite function call on two lines for clarity (#79141)
* 443e23eed24d Bump version to 18.1.8 (#95458)
Release announcement [1]
[1] https://discourse.llvm.org/t/18-1-8-released/79725/1
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the …
> clang: Upgrade to 18.1.8

- recipes-devtools/clang/clang_git.bb
Fixes
ERROR: clang-19.0.0-r0 do_package: QA Issue: clang: Files/directories were installed but not shipped in any package:
/usr/share/clang-doc
/usr/share/clang-doc/clang-doc-default-stylesheet.css
/usr/share/clang-doc/index.js
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but want …
> clang: Package docs related to clang-doc tool

- conf/nonclangable.conf
Somehow linker/lld here fails to link ptests with cargo, therefore workaround it by disabling lld when ptest feature is on.
Fixes errors like
note: riscv64-yoe-linux-ld.lld: error: undefined symbol: PyExc_ValueError\nreferenced by bcrypt_rust.a93ef5fbf090e743-cgu.0
--- …
> python-bcrypt: Do not use lld when building with ptests on.

- classes/clang.bbclass
Currently, only the '-mcpu=octeontx2' option is removed, and any -mcpu parameters with qualifiers (such as +crc+crypto) are not removed, e.g., '-mcpu=octeontx2+crypto'. Remove these mcpu parameters with qualifiers by using '-mcpu=octeontx2${TUNE_CCARGS_MARCH_OPTS}'.
--- …
> clang.bbclass: remove mcpu option with qualifiers for the octeontx2 core

- recipes-devtools/clang/clang_git.bb
Enable it by default, since it is needed for debuginfod to work
Fixes https://github.com/kraj/meta-clang/issues/956
---
> clang: Add packageconfig option for build-id

- recipes-devtools/clang/nativesdk-clang-glue.bb
SPDX 3.0 has this task executing but other tasks which it depends on are deleted, delete this one too.
---
> nativesdk-clang-glue: Delete do_create_package_spdx task

- recipes-devtools/clang/libcxx_git.bb
On arm64 OE-Core has moved the gcc default configuration done with --enable-standard-branch-protection to be a CFLAGS option which is appended to CC variable, this means that this option can override the package's default to not use it e.g. libunwind where the library has to be built without it.
Fixes https://github.com/kraj/meta-clang/issues/963
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you …
> libcxx: Do not induce -mbranch-protection externally on arm64

- conf/nonclangable.conf
Some ptests do not build with LLD on RISCV64
| riscv64-yoe-linux-ld: error: undefined symbol: __stop___debug | >>> referenced by log.c:168 (/usr/src/debug/bluez5/5.76/../bluez-5.76/src/log.c:168)
| >>>               src/log.o:(__btd_log_init)
|
| riscv64-yoe-linux-ld: error: undefined symbol: __start___debug
| >>> referenced by log.c:168 (/usr/src/debug/bluez5/5.76/../bluez-5.76/src/log.c:168)
| >>>               src/log.o:(__btd_log_init)
| >>> the encapsulation symbol needs to be retained under --gc-sections properly; consider -z nostart-stop-gc (see https://lld.llvm.org/ELF/start-stop-gc)
---
- '*Request Changes*' …
> bluez5: Use BFD linker

- recipes-devtools/llvm/llvm_%.bbappend
…t failed
Due to commit [1][2], llvm-native was added to bpftrace to provide llvm-objcopy for the ptest.
But because of commit [3], llvm-native requires opengl in DISTRO_FEATURES to support libllvm.
In order to make the build of bpftrace ptest work, explicitly add libllvm to PACKAGECONFIG for llvm-native if ptest enabled.
According to [2][3], bpftrace used llvm-objcopy to generate BTF data for unit tests, regardless opengl in DISTRO_FEATURES, enable accelerated software renderer or not does not have side effect on bpftrace
[1] https://github.com/kraj/meta-clang/commit/bf6c02a47fb2ffec735df6c7dd642432f3681337
[2] https://github.com/bpftrace/bpftrace/commit/6cc531e35cd3bf77aa2a30cef3e3481c9c53042e
[3] https://git.openembedded.org/openembedded-core/commit/?id=ec22bfa67f6f1766102501d4593ce29aa …
> Fix the build of bpftrace ptest failed

- recipes-devtools/clang/libcxx_git.bb
Backport https://github.com/kraj/meta-clang/pull/968
On arm64 OE-Core has moved the gcc default configuration done with --enable-standard-branch-protection to be a CFLAGS option which is appended to CC variable, this means that this option can override the package's default to not use it e.g. libunwind where the library has to be built without it.
Fixes https://github.com/kraj/meta-clang/issues/963
---
- '*Comment*' if you don't feel you have …
> kirkstone[backport] libcxx: Do not induce -mbranch-protection externally on arm64

- dynamic-layers/qt6-layer/recpes-qt/qt6/qtbase_%.bbappend
chromium has certain options e.g. -Wl,-mllvm,xxx
assumed when compiler chosen is clang. These options are not understood by GNU linker, therefore force
using LLD when clang toolchain is used to compile
QT6 components.
--- …
> qt6/qtbase: Always use lld linker with clang

- recipes-devtools/clang/clang_git.bb
LLVM_EXPERIMENTAL_TARGETS_TO_BUILD is appended with the value of get_clang_experimental_target_arch() which is just the value of get_clang_experimental_arch which is always the empty string despite appearances.
Thus none of this is useful, remove it.
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully …
> clang: remove pointless experimental targets code

- conf/nonclangable.conf
- recipes-devtools/bindgen-cli/bindgen-cli-crates.inc
- recipes-devtools/bindgen-cli/bindgen-cli_0.69.4.bb
Since its being build from kernel sources which are procecced with gcc by default KERNEL_CC is gcc, its a constant battle to keep this compiling with clang, so unless clang is also used to compile kernel this is a fruitless excercise to use clang just for perf.
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to …
> perf: Use gcc as default compiler

- recipes-devtools/include-what-you-use/include-what-you-use_0.22.bb
Clang based checker for C/C++ header includes. "Experimental software, as of June 2024.", but definitely very useful.
---
> include-what-you-use: new recipe

- recipes-devtools/clang/compiler-rt-sanitizers_git.bb
Native builds of compiler-rt-sanitizers fail because llvm-ranlib, llvm-ar, and llvm-nm are not found where the recipe specifies that they'll be. Other recipes (in particular: compiler-rt) only specify the locations of those tools for target and nativesdk builds, and they build fine. This commit implements the same thing for compiler-rt-sanitizers, fixing native builds.
Note that there seems to be a separate issue with `compiler-rt-sanitizers` failing to build with `-DCOMPILER_RT_USE_BUILTINS_LIBRARY=ON` as is specified in the recipe. But with that set to `OFF`, the package fails to build as described above without this patch, and successfully builds with it applied.
---
- '*Approve*' if this change would be acceptable in the codebase (even if there …
> compiler-rt-sanitizers: Fix native build tooling paths

- recipes-devtools/clang/clang_git.bb
Currently, class-target is reproducible, but class-nativesdk is not. What I did:
- noticed that BuildVariables.inc contains meaningless path fragments after running sed, so I adjusted sed commands to remove the rest of paths as well;
- moved common code into a function, which is then called twice;
- changed do_compile:prepend into do_configure:append, this is more conventional and intuitive;
- verified that the resulting code works for both target and nativesdk after these changes.
---
- '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in …
> clang: improve reproducibility

- recipes-devtools/clang/libclc_git.bb
The cmake-qemu class handles using qemu-user as a CMake emulator, so use that and clean up the recipe.
> libclc: use cmake-qemu to clean up recipe

- conf/layer.conf
- recipes-devtools/clang/clang.inc
- recipes-devtools/clang/common.inc
oe-core updated llvm to 18.1.6, let's keep the clang version in sync
---
> clang: Upgrade to 18.1.6

- conf/nonclangable.conf
- recipes-devtools/clang/libcxx_git.bb
On aarch64 the handling of runtime exception is broken when build with clang.
There is currently a fix for libcxx on the layer but it is not enough and this same fix needs to be applied globally.
First fix attempt just include libcxx:
https://github.com/kraj/meta-clang/issues/963
https://github.com/kraj/meta-clang/pull/968
Remaining reported issue:
https://github.com/kraj/meta-clang/issues/998
---
- '*Comment*' if you don't feel you have …
> layer.conf: remove '-mbranch-protection=standard' globally on aarch64

- conf/nonclangable.conf
Its still needed with clang-18 with libc++
---
> vulkan-samples: Re-introduce -Wno-error=deprecated-declarations

- dynamic-layers/qt6-layer/recpes-qt/qt6/qtwebengine_%.bbappend
This makes the chromium build less confused when mixing native compiler for gcc and target compiler for clang this does not sit well with gn build system and it starts to pass clang options to gcc, which does not always work
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but want to …
> qtwebengine: Use clang for native toolchain as well

- recipes-devtools/clang/clang_git.bb
This tool is unmaintained and clang-20+ has removed it [1]
[1] https://github.com/llvm/llvm-project/commit/ed8f78827895050442f544edef2933a60d4a7935
---
> clang: Do not package clang-pseudo-gen

- conf/nonclangable.conf
This issue has been resolved upstream:
https://gitlab.gnome.org/GNOME/vte/-/commit/c8838779d5f8c0e03411cef9775cd8f5a10a6204
This reverts commit 70295d739f830a8d2abb2ad961e1c544f01be197.
---
> Revert "vte: Use libstdc++ when using clang"

- conf/nonclangable.conf
Since clang is at version 19 now, remove the blocking of building u-boot.  I'm not seeing any issues with building u-boot and running testimage for qemuarm, qemuarm64, and qemumips.
Based on the original comment, this limitation probably should've been only applied to mips.
Leaving the BSP versions of u-boot in nonclangable, as I don't know if those have issues or not, and thought it better to err on the side of caution.
> u-boot: u-boot is clangable

- conf/layer.conf
- recipes-devtools/clang/llvm-project-source.bb
While enabling multilib, build lib32-llvm-project-source-19.1.0 and llvm-project-source-19.1.0 at the same time:
$ MACHINE = "qemux86-64"
$ require conf/multilib.conf
$ MULTILIBS = "multilib:lib32"
$ DEFAULTTUNE:virtclass-multilib-lib32 = "x86"
$ bitbake lib32-llvm-project-source-19.1.0 llvm-project-source-19.1.0
...
$ cat tmp/work-shared/llvm-project-source-19.1.0-r0/temp/log.task_order
20241012-070604.819630 do_recipe_qa (2728706): log.do_recipe_qa.2728706
20241012-070604.883194 do_recipe_qa (2728707): log.do_recipe_qa.2728707
20241012-070605.037448 do_fetch (2728779): log.do_fetch.2728779
20241012-070605.165280 do_fetch (2728848): log.do_fetch.2728848
20241012-071030.798104 do_unpack (2733554): log.do_unpack.2733554
20241012-071030.864536 do_unpack (2733559): log.do_unpack.2733559 …
> Fix racing on building lib32-llvm-project-source-19.1.0 and llvm-project-source-19.1.0

- conf/nonclangable.conf
libc++ seems to result in test failures, perhaps something to fix in toml++ but it needs to be triaged.
---
> tomlplusplus: Pin to use libstdc++ with clang

- conf/nonclangable.conf
glibc static library expects builtins from libgcc which may not exist in compiler-rt, therefore use libgcc explicitly.
---
> ostree: Use libcc for compiler runtime when using glibc for system

- recipes-connectivity/openssl/openssl_%.bbappend
Additionally disable relaxation on rv32 with lld see [1]
[1] https://github.com/llvm/llvm-project/issues/113838
---
> openssl: Drop riscv workarounds to add libatomic

- recipes-devtools/spirv-llvm-translator/spirv-llvm-translator_git.bb
* branch was renamed long time ago, nanbield and newer already have this updated since: 
2d9f57f spirv-llvm-translator: Update to latest 16.0.0 branch
but kirkstone was still using master
> spirv-llvm-translator: update SPIRV-Headers branch from master to main

- recipes-devtools/clang/clang_git.bb
With these settings, we'll have multiple providers of llvm. This means that with pristine poky master + meta-clang master, we'll have some output like below:
NOTE: Multiple providers are available for llvm-native (llvm-native, clang-native)
Consider defining a PREFERRED_PROVIDER entry to match llvm-native
And when running 'bitbake world', we'll get error messages like below:
ERROR: Multiple .bb files are due to be built which each provide llvm-native:
virtual:native:/PATH/TO/poky/meta/recipes-devtools/llvm/llvm_19.1.4.bb
virtual:native:/PATH/TO/Yocto/poky/meta-clang/recipes-devtools/clang/clang_git.bb
As the README.md has already specified how to use this layer, let's remove such settings before sorting things out.
---
- '*Approve*' if this change …
> clang: remove PROVIDES:append settings

- conf/nonclangable.conf
Clang generates _atomic_store calls
---
> lttng-ust: Link with libatomic on 32bit x86

- recipes-devtools/clang/clang_git.bb
getVar() now defaults to expanding by default,
thus remove the True option from getVar() calls
with a regex search and replace.
Signed-off-by: Akash Hadke <akash.hadke27@gmail.com>
---
> clang_git.bb: Remove True option to getVar calls

- classes/clang.bbclass
- conf/layer.conf
- recipes-core/musl/musl_%.bbappend
- recipes-devtools/clang/clang-cross-canadian_git.bb
- recipes-devtools/clang/clang-cross_git.bb
- recipes-devtools/clang/clang-crosssdk_git.bb
- recipes-devtools/clang/clang_git.bb
- recipes-devtools/clang/compiler-rt-sanitizers_git.bb
- recipes-devtools/clang/compiler-rt_git.bb
- recipes-devtools/clang/libcxx_git.bb
[Khem: This updates meta-clang to match the virtual/ providers changes likely to merge soon to OE-Core]
Update meta-clang to match OE-Core changes to use recipe specific virtual providers (without yet switching to the new switching mechanism).
--- …
> recipes: Update to match OE-Core virtual/cross-* changes

- conf/nonclangable.conf
LLD does not understand the linker script versioning scheme as BFD linker does
---
> libslirp,avahi-libnss-mdns: Add --undefined-version to LDFLAGS with LLD

- recipes-devtools/clang/clang/0040-Install-arm_neon_sve_bridge.h.patch
- recipes-devtools/clang/common.inc
During building clang, arm_neon_sve_bridge.h is not copied to the correct destination folder, failing the compilation of applications using this header.
This has been fixed upstream starting in [clang 16](https://github.com/llvm/llvm-project/commit/8cb9e3c3ce1e7e1658921f90420b68ca16bb98fc). This patch is a backport of the fix, only for Kirkstone branch.
The changes have been tested by building clang-native, and using it to compile Firefox (which failed previously, due to this missing header)
---
- '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development …
> [kirkstone] clang-native: install arm_neon_sve_bridge.h header

- conf/nonclangable.conf
Somehow g-i parser is confused with glibc 2.41 headers on x86-64 as well when using clang, it works ok when using gcc
---
> libmodulemd,libblockdev,webkitgtk: Disable g-i on x86-64

- recipes-devtools/clang/common.inc
- recipes-devtools/clang/compiler-rt-sanitizers_git.bb
- recipes-devtools/clang/compiler-rt_git.bb
- recipes-devtools/clang/libclc_git.bb
- recipes-devtools/clang/libcxx_git.bb
- recipes-devtools/clang/openmp_git.bb
Similar gcc recipes in oe-core [1], set BPN = "clang" in common.inc for clang cross,crosssdk,cross-canadian recipes, but the recipe compiler-rt-sanitizers, compiler-rt, libclc, libcxx, openmp which shares sources with clang are not affected
Due to commit [2], the BPN of llvm-project-source is not affected by this commit
[1] https://github.com/openembedded/openembedded-core/commit/a2c5509520d5c3e082f55844e6545d0309565f8f
[2] https://github.com/kraj/meta-clang/commit/e7517e1910a7d49abb4782fa0778f0b958f7717d
---
- '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will …
> clang: set BPN = "clang" for clang cross,crosssdk,cross-canadian recipes

- recipes-devtools/clang/clang_git.bb
In certain configurations LLVMConfig.cmake does not exist in the build output. If that's the case do_install breaks for the nativesdk-clang recipe.
To reproduce set the following on a vanilla build:
EXTRA_OECMAKE:append:pn-nativesdk-clang = " -DLLVM_INSTALL_TOOLCHAIN_ONLY=ON"
as suggested here:
https://llvm.org/docs/BuildingADistribution.html
The corresponding issue #1061 blames commit f002eb5a but 716d7efb is also to blame and it is not ruled out that the problem could affect other configurations and other tasks.
**Question**: 716d7efb is from Oct. 2023 - so for a while out in the wild. But nobody seems to have similar problems like we have. If we remove the EXTRA_OECMAKE:append the build works fine. Does noone actually builds clang with the suggestd EXTRA_OECMAKE:append, or why is it …
> fix: [Issue #1061] - check for existence before trying to process a file

- conf/nonclangable.conf
- recipes-devtools/clang/clang/0036-Fix-build-on-ppc64-musl.patch
- recipes-devtools/clang/common.inc
> Fix sanitizers and webkit builds on riscv

- conf/layer.conf
- recipes-devtools/clang/clang.inc
- recipes-devtools/clang/common.inc
* 424c2d9b7e4d [libcxx] Add a missing include for __bit_iterator (#127015)
* 2cc53628fbe8 [SCEV] Check whether the start is non-zero in `ScalarEvolution::howFarToZero` (#131522)
* 0619bbcbbd86 [BPF] Add default cpu change in ReleaseNotes (#131691)
* 2dc152fb40db fix abi (again)
* 2044b18af046 fix abi
* e3f0ce3ef803 [Clang] Do not emit nodiscard warnings for the base expr of static member access (#131450)
* 0ceb4efefeaa [CUDA][HIP] fix virtual dtor host/device attr (#128926)
* 1058e693f090 [libc++][test] Skip a `is_virtual_base_of` test for apple-clang-17 (#131438)
* 1f9d00524b8c [libc++] Forward-proof some tests for AppleClang 17
* 1515c4ac202d [LAA] Consider accessed addrspace when mapping underlying obj to access. (#129087)
* 1cfbb9f33436 Backport/20.x: [Clang] Fix an incorrect …
> clang: Upgrade to 20.1.1

- dynamic-layers/openembedded-layer/recipes-devtools/bpftrace/bpftrace_0.20.1.bb
- recipes-kernel/libbpf/libbpf/0001-bpf-Add-btf-enum64-support.patch
- recipes-kernel/libbpf/libbpf/0001-bpf-Add-cookie-support-to-programs-attached-with-kpr.patch
- recipes-kernel/libbpf/libbpf/0001-bpf-Add-multi-kprobe-link.patch
- recipes-kernel/libbpf/libbpf/0001-libbpf-Add-bpf_link_create-support-for-multi-kprobes.patch
- recipes-kernel/libbpf/libbpf/0001-libbpf-Add-enum64-parsing-and-new-enum64-public-API.patch
- recipes-kernel/libbpf/libbpf/0001-libbpf-Add-enum64-sanitization.patch
- recipes-kernel/libbpf/libbpf/0001-libbpf-Introduce-bpf_-btf-link-map-prog-_get_info_by.patch
- recipes-kernel/libbpf/libbpf/0001-libbpf-Refactor-btf__add_enum-for-future-code-sharin.patch
- recipes-kernel/libbpf/libbpf_%.bbappend
Fix bcc do_compile failure and bpftrace do_configure, do_compile errors in kirkstone-clang18.
> Fix bcc do_compile and bpftrace do_configure/do_compile errors

- recipes-devtools/clang/clang/0037-clangd-Add-a-build-option-to-disable-building-dexp.patch
- recipes-devtools/clang/clang_git.bb
- recipes-devtools/clang/common.inc
Building dexp (native) on Debian 11 causes intermittent failure[0]. This tools in not used in clang except in tests (that we don't run).
So, disable building this tool by encapsulating its build in a cmake option and then in a PACKAGECONFIG.
Users sure of not using Debian 11 (or the impacted g++ compiler) can turn this config on safely.
Only the -native* variants change. Dexp is still enabled by default for target.
[0]: https://bugzilla.yoctoproject.org/show_bug.cgi?id=15803
---
* Built clang-native
* Verified that Dexp.cpp has **not** been compiled 
- '*Request Changes*' if this change would not be acceptable in our …
> clang: Disable building dexp in clang-native

- conf/nonclangable.conf
This supresses the -msseX argument diagnostics on non-x86 architectures and meson wrongly decided to enable SSE on these biulds which ends up in
│
│| In file included from ../gimp-3.0.2/app/gegl/gimp-gegl-loops-sse2.c:36:                                                                                                               │
│| /mnt/b/yoe/master/build/tmp/work/riscv64-yoe-linux/gimp/3.0.2/recipe-sysroot-native/usr/lib/clang/20/include/emmintrin.h:14:2: error: "This header is only meant to be used on x86 and│
│ x64 architecture"                                                                                                                                                                      │
│|    14 | #error "This header is only meant to be used on x86 and x64 architecture" …
> gimp: Remove -Qunused-arguments from complier cmdline with clang

- conf/layer.conf
The LLVM package in OE-Core got optional support for building libclc and SPIRV-LLVM-Translator. However this also means that llvm-native also install clang binaries into the sysroot. In order to remove a conflict with the clang recipe from meta-clang forcibly disable PACKAGECONFIG options causing conflict.
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't …
> layer.conf: disable conflicting LLVM PACKAGECONFIG options

- conf/layer.conf
- recipes-devtools/clang/clang.inc
- recipes-devtools/clang/common.inc
* 58df0ef89dd6 Define LLVM_ABI and CLANG_ABI for __EMSCRIPTEN__ builds (#131578)
* e256eda15377 [LoongArch][MC] Add relocation support for fld fst [x]vld [x]vst
* ba00d9f641e9 [LoongArch] Pre-commit test for #133225
* f07f96873aa8 Backport/20.x: [LoongArch] Fix the type of tls-le symbols
* e7406753caf3 [PATCH] [clang][modules] Fix serialization and de-serialization of PCH module file refs  (#105994) (#132802)
* 2f6c5807ca7e [workflows] Add missing -y option to apt-get for abi tests (#133337)
* bc65196c0919 update test due to https://github.com/llvm/llvm-project/pull/126880 not being backported
* d6d1dbf22181 [ARM] Speedups for CombineBaseUpdate. (#129725)
* 5ba194972878 [MC,COFF] .safeseh: avoid changeSection (#132624)
* 943b43250b55 release/20.x: [clang][docs] Move -Wnontrivial-memcall …
> clang: Upgrade to 20.1.2 release

- dynamic-layers/meta-python/recipes-devtools/bpftrace/bpftrace_0.23.0.bb
This option mostly enables sd_notify support and is useful when running bpftrace as part of a systemd service [1].
Defaulting to the systemd DISTRO_FEATURES seems like a reasonable choice. The official builds also now enable this by default [2].
[1] https://bpftrace.org/docs/latest#_systemd_support
[2] https://github.com/bpftrace/bpftrace/pull/3969
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if …
> bpftrace: add systemd PACKAGECONFIG option

- dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc/CVE-2024-2314.patch
- dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc_0.24.0.bb
If kernel headers need to be extracted, bcc will attempt to load them from a temporary directory. An unprivileged attacker could use this to force bcc to load compromised linux headers. Linux distributions which provide kernel headers by default are not affected by default.
Reference:
https://nvd.nist.gov/vuln/detail/CVE-2024-2314
Upstream-patch:
https://github.com/iovisor/bcc/commit/008ea09e891194c072f2a9305a3c872a241dc342
Signed-off-by: Divya Chellam <divya.chellam@windriver.com>
---
> bcc: fix CVE-2024-2314

- dynamic-layers/meta-python/recipes-devtools/bpftrace/bpftrace_0.23.0.bb
Update SRCREV to tag 0.23.0, refer [1]
[1] https://github.com/bpftrace/bpftrace/releases/tag/v0.23.0
---
> bpftrace: update SRCREV to tag 0.23.0

- recipes-devtools/clang/clang/0033-llvm-Add-libunwind.pc.in-and-llvm-config-scripts.patch
- recipes-devtools/clang/clang_git.bb
- recipes-devtools/spirv-llvm-translator/spirv-llvm-translator_git.bb
Several more patches for meta-clang, resolving sysroot-native conflict when building Mesa with libclc
---
> More fixes for meta-clang vs OE-Core

- recipes-devtools/clang/clang_git.bb
Modify the clang recipe to provide also the python module 'clang' when building libclang.
---
> clang: Include the libclang python bindings in the build

- dynamic-layers/meta-python/recipes-devtools/bcc/bcc/run-ptest
when running ptest for bcc we need to
export BCC_KERNEL_SOURCE to resolve test errors.
---
> bcc: export BCC_KERNEL_SOURCE in run-ptest

- recipes-devtools/clang/clang-cross-canadian_git.bb
- recipes-devtools/clang/clang-crosssdk_git.bb
- recipes-devtools/clang/clang_git.bb
This reverts commit e7b3acb82f4c4422e57884ad9427fba6bd020e8b.
This change was originally made in scarthgap and later backported to kirkstone-clang18. However, oe-core kirkstone still uses 'virtual/${TARGET_PREFIX}binutils-crosssdk'.
Reverting to maintain compatibility with oe-core kirkstone.
Signed-off-by: Soumya Sambu <soumya.sambu@windriver.com>
---
- '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you …
> Revert "Drop crosssdk suffix from virtual binutils provides to match oe-core"

- recipes-devtools/castxml/castxml_0.6.11.bb
- recipes-devtools/include-what-you-use/include-what-you-use_0.23.bb
Due to recent UNPACKDIR/S change in oe-core, the S settings in these two recipes are no longer valid and are causing errors. Remove them.
---
> castxml/include-what-you-use: remove incorrect S settings

- README.md
- conf/layer.conf
- recipes-devtools/clang/clang_git.bb
This reverts commit 384e8d169a2c408e2cef03ea2deb88fb82058011.
The original commit removed the implicit PROVIDES declarations for llvm, llvm-native, and nativesdk-llvm from the clang recipe.
However, this change breaks builds in kirkstone-clang18 environments, where mesa and lib32-llvm expect these to be provided by clang:
- Mesa fails due to missing providers for llvm18.1.6 and nativesdk-llvm18.1.6.
- lib32-llvm 13.0.1 fails on ARM BSPs with the following error, falling back to the core layer's outdated LLVM:
error: 'RegVT' was not declared in this scope
This commit was backported from scarthgap, but it is incompatible with oe-core expectations in the kirkstone branch. Reverting it restores compatibility.
---
- '*Approve*' if this change would be …
> Revert "clang: Do not provide llvm-native implicitly"

- classes/clang.bbclass
This reverts commit 4e0da29d9bca9ab7091abcbb59dd439c09319ca8.
This commit was backported from scarthgap to kirkstone-clang18 and is incompatible with oe-core kirkstone tune configuration. Reverting to align with oe-core.
Signed-off-by: Soumya Sambu <soumya.sambu@windriver.com>
--- …
> Revert "clang.bbclass: remove mcpu option with qualifiers for the octeontx2 core"

- recipes-devtools/clang/compiler-rt-sanitizers_git.bb
Currently compiler-rt-sanitizers fails to build as native recipe. Configuration log shows:
-- Compiler-RT supported architectures: x86_64
-- Failed to find compiler-rt builtins library for x86_64-linux
The reasons is that calling
`clang --rtlib=compiler-rt -print-libgcc-file-name`
returns (tested in devshell and via additional cmake logs)
`/usr/lib/clang/18.1.6/lib/linux/libclang_rt.builtins-x86_64.a`
which is missing the recipe-sysroot-native prefix.
COMPILER_RT_USE_BUILTINS_LIBRARY=OFF is implemented in kirkstone and also in master (in core). Note that when moving clang from meta-clang to core, I didn't find explanation why this was changed back, but I assume that it was because of issues like this.
When running
`clang --rtlib=compiler-rt -print-libgcc-file-name`
on master, it correctly …
> compiler-rt-sanitizers: disable builtins library

- classes/clang.bbclass
- conf/layer.conf
- recipes-core/musl/musl_%.bbappend
- recipes-devtools/clang/clang-cross-canadian_git.bb
- recipes-devtools/clang/clang-cross_git.bb
- recipes-devtools/clang/clang-crosssdk_git.bb
- recipes-devtools/clang/clang_git.bb
- recipes-devtools/clang/compiler-rt-sanitizers_git.bb
- recipes-devtools/clang/compiler-rt_git.bb
- recipes-devtools/clang/libcxx_git.bb
This reverts commit 0ea2df0462edc0c01e787b6ee6c0e20cd6a42fc7.
Required backport to match the OE-Core machanism in scarthgap
> Revert "recipes: Update to match OE-Core virtual/cross-* changes"

- dynamic-layers/meta-python/recipes-devtools/bcc/bcc_0.33.0.bb
`UNPACKDIR` has not been introduced to scarthgap, remove it.
> [scarthgap-clang20] Revert UNPACKDIR usage

- dynamic-layers/selinux/android-tools/android-tools_10.0.0.r36.bb
remove use of nobranch=1 so that source
can be pick up from master branch
For libhardware SRCREV not present in
master branch so mentioned the branch
android10-qpr2-release
Signed-off-by: Nitin Wankhade <nitin.wankhade333@gmail.com>
---
> android-tools: Remove use of nobranch

- recipes-devtools/clang/compiler-rt_git.bb
When LLVM_LIBDIR_SUFFIX is set we were creating
.../clang/${MAJOR_VER}.${MINOR_VER}.${PATCH_VER}/lib and moving ${libdir}/linux there. On targets where ${libdir} == lib64 (or other), this hard-codes the wrong directory and can lead to a mismatched layout.
Use ${baselib} so the installed library path follows the target’s base library dir (lib, lib64, etc.), matching Yocto multilib expectations.
---
- '*Comment*' if you don't feel you have …
> compiler-rt: install into ${baselib} instead of a fixed lib dir

- conf/nonclangable.conf
This has adverse effect now with clang-21 on riscv64 qemu where opensbi ends up not being found during boot and qemu getting stuck in early boot.
---
> opensbi: Do not enforce objcopy from binutils for clang
